export const TreemapOrder:Object = [
    { 'path': 'treemap/default', 'component':'Default', 'name': 'Default Functionalities', 'description':'This demo for Essential JS2 TreeMap control visualizes the sales of cars across various countries in 2017.', 'order': '01', 'category': 'TreeMap' },
    { 'path': 'treemap/layout', 'component':'Layout', 'name': 'Layout', 'description':'This demo for Essential JS2 TreeMap control illustrates the GDP nominal of top 10 countries in the year 2015. The layout of the TreeMap can also be changed.', 'order': '01', 'category': 'TreeMap' },
    { 'path': 'treemap/drilldown', 'component':'Drilldown', 'name': 'Drilldown', 'description':'This demo for Essential JS2 TreeMap control demonstrates drill-down with the continents at the top level followed by regions and countries.', 'order': '01', 'category': 'TreeMap' },
    { 'path': 'treemap/customization', 'component':'Customization', 'name': 'Customization', 'description':'This demo for Essential JS2 TreeMap control depicts the gold medal categories of the 2016 US Summer Olympics. Each category is denoted with label template.', 'order': '01', 'category': 'TreeMap' },
    { 'path': 'treemap/label', 'component':'Datalabel', 'name': 'Data Label', 'description':'This demo for Essential JS2 TreeMap control depicts the population level of various countries in 2017 along with data labels.', 'order': '01', 'category': 'TreeMap' },
    { 'path': 'treemap/tooltip', 'component':'Tooltip', 'name': 'Tooltip', 'description':'This demo for Essential JS2 TreeMap control depicts the number of international airports available in various countries in South America along with tooltip.', 'order': '01', 'category': 'TreeMap' },
    { 'path': 'treemap/election', 'component':'Legend', 'name': 'Legend', 'description':'This demo for Essential JS2 TreeMap control visualizes the 2016 U.S.A. presidential election results. Default and interactive are the two types of legend.', 'order': '01', 'type': 'update', 'category': 'TreeMap' },
    { 'path': 'treemap/color-mapping', 'component': 'ColorMapping', 'name': 'Color Mapping', 'type': 'new', 'description': 'This demo for Essential JS2 TreeMap control visualizes the population level of various continents in 2011 based on the gender and age group.', 'order': '01', 'category': 'TreeMap' },
    { 'path': 'treemap/selection', 'component':'Selection', 'name': 'Selection & Highlight', 'description':'This demo for Essential JS2 TreeMap control depicts the details of goods imported by Japan. Selection and highlight options have been enabled.', 'order': '01', 'category': 'TreeMap' },
    { 'path': 'treemap/print', 'component':'Print', 'name': 'Print & Export', 'description':'This demo for Essential JS2 TreeMap control depicts the top 10 best-selling smartphone brands. Print and export options have been enabled.', 'order': '01', 'category': 'TreeMap' },
    { 'path': 'treemap/pie', 'component':'Pie', 'name': 'Treemap with Pie', 'description':'This demo for Essential JS2 TreeMap control visualizes the population level of various continents in 2011 based on the gender and age group.', 'order': '01', 'category': 'TreeMap' }
]