export const SliderSampleOrder: Object = [
    { 'path': 'range-slider/default', 'component': 'Default', 'name': 'Default Functionalities', 'description': 'Essential<sup>®</sup> JS 2 slider control demo showing the default rendering of default, minimum range, and range sliders. Drag the thumb to interact with the slider.', 'order': '01', 'category': 'Range Slider', 'api': '{"SliderComponent": ["value", "type", "appendTo"]}' },
    { 'path': 'range-slider/ticks', 'component': 'Ticks', 'name': 'Ticks', 'description': 'Essential<sup>®</sup> JS 2 slider control demo of the visual representation of slider values using ticks, which can be placed before, after, or on both sides of the thumbs.', 'order': '01', 'category': 'Range Slider', 'api': '{"SliderComponent": ["value", "type", "appendTo", "enabled"]}' },
    { 'path': 'range-slider/tooltip', 'component': 'Tooltip', 'name': 'Tooltip', 'description': 'Essential<sup>®</sup> JS 2 slider control demo of the visual representation of slider values using tooltips, which can be displayed before or after slider thumbs.', 'order': '01', 'category': 'Range Slider', 'api': '{"SliderComponent": ["value", "type", "appendTo", "showButtons", "dragInterval"]}' },
    { 'path': 'range-slider/orientation', 'component': 'Orientation', 'name': 'Vertical Orientation', 'description': 'Essential<sup>®</sup> JS 2 slider control demo showing the vertical and horizontal orientation properties along with ticks and tooltips.', 'order': '01', 'category': 'Range Slider', 'api': '{"SliderComponent": ["value", "type", "appendTo", "orientation", "dragInterval"]}' },
    { 'path': 'range-slider/format', 'component': 'Format', 'name': 'Formatting', 'description': 'Demo of Essential<sup>®</sup> JS 2 slider control value formatting with time, currency, and distance values that are also displayed in ticks and tooltips.', 'order': '01', 'category': 'Range Slider', 'api': '{"SliderComponent": ["value", "type", "appendTo","min", "max", "step", "tooltipChange", "renderingTicks"]}' },
    { 'path': 'range-slider/limits', 'component': 'Limits', 'name': 'Limits', 'description': 'Essential<sup>®</sup> JS 2 slider control demo of limiting the minimum, maximum, start, and end values. Also supports restricting handle movements.', 'order': '01', 'category': 'Range Slider', 'api': '{"SliderComponent": ["value", "type", "appendTo","min", "max", "limits", "minStart", "minEnd", "maxStart", "maxEnd", "startHandleFixed", "endHandleFixed"]}' },
    { 'path': 'range-slider/api', 'component': 'APIs', 'name': 'API', 'description': 'Essential<sup>®</sup> JS 2 slider control demo showcasing the most frequently used API combinations, like orientation, minimum, maximum, value, step, and more.', 'order': '01', 'category': 'Range Slider', 'api': '{"SliderComponent": ["value", "type", "appendTo","min", "max", "step", "showButtons", "readOnly","enabled","orientation"]}' },
    { 'path': 'range-slider/events', 'component': 'Events', 'name': 'Events', 'description': 'Demo of the Essential<sup>®</sup> JS 2 slider control created, changing, and changed events. The events are traced in real time in a property panel.', 'order': '01', 'category': 'Range Slider', 'api': '{"SliderComponent": ["value", "type", "appendTo","change", "create", "created"]}' },
    { 'path': 'range-slider/thumb-customization', 'component': 'Thumb', 'name': 'Thumb', 'description': 'Demo of the Essential<sup>®</sup> JS 2 slider control slider thumb customization with circle, oval, and custom image shapes.', 'order': '02', 'category': 'Customization', 'api': '{"SliderComponent": ["value", "type", "appendTo","min", "max"]}' },
    { 'path': 'range-slider/selection-bar-customization', 'component': 'Bar', 'name': 'Bar', 'description': 'This example demonstrates how to highly customize Syncfusion<sup>®</sup> React slider bar with colors and height.', 'order': '02', 'category': 'Customization', 'api': '{"SliderComponent": ["value", "type", "appendTo","min", "max", "change", "created"]}', 'sourceFiles': [
        { 'displayName': 'selection-bar-customization.tsx', 'path': 'src/range-slider/selection-bar-customization.tsx' },{ 'displayName': 'selection-bar-customization.jsx', 'path': 'src/range-slider/selection-bar-customization.jsx' },{ 'displayName': 'bar.css', 'path': 'src/range-slider/bar.css'}] },
    { 'path': 'range-slider/ticks-customization', 'component': 'TicksCustomization', 'name': 'Ticks', 'description': 'Essential<sup>®</sup> JS 2 slider control demo showing the highly customizable slider values using ticks and a legend.', 'order': '02', 'category': 'Customization', 'api': '{"SliderComponent": ["value", "type", "appendTo","min", "max", "step", "renderingTicks", "renderedTicks"]}', 'sourceFiles': [
        { 'displayName': 'ticks-customization.tsx', 'path': 'src/range-slider/ticks-customization.tsx' },{ 'displayName': 'ticks-customization.jsx', 'path': 'src/range-slider/ticks-customization.jsx' },{ 'displayName': 'ticks-customization.css', 'path': 'src/range-slider/ticks-customization.css' }] },
    { 'path': 'range-slider/tooltip-customization', 'component': 'TooltipCustomization', 'name': 'Tooltip', 'description': 'Demo of Essential<sup>®</sup> JS 2 slider control customization of slider tooltip text and background color with formatted text values.', 'order': '02', 'category': 'Customization', 'api': '{"SliderComponent": ["value", "type", "appendTo","min", "max", "step", "tooltipChange", "renderingTicks", "created"]}' },
    { 'path': 'range-slider/azure-pricing', 'component': 'Cloudpricing', 'name': 'Cloud Pricing', 'description': 'This example demonstrates the usage of Syncfusion<sup>®</sup> React slider control in real world use case sample azure cloud pricing.', 'order': '03', 'category': 'Use Case', 'api': '{"SliderComponent": ["value", "type", "appendTo","min", "max", "step","created"]}' }
]
