export const TreeGridSampleOrder: Object = [
  { 'path': 'treegrid/treegrid-overview', 'component': 'Overview', 'name': 'Overview', 'description':'This React Tree Grid example demonstrates the overview in React Tree Grid Component. Explore here for more details.', 'order': '01', 'category': 'Tree Grid' ,'api':'{"TreeGridComponent":["queryCellInfo","dataSource","enableVirtualization","allowFiltering","allowSorting","allowSelection","selectionSettings","height","columns","dataBound","actionComplete","load"] }',
    'sourceFiles': [{ 'displayName': 'treegrid-overview.tsx', 'path': 'src/treegrid/treegrid-overview.tsx' }, { 'displayName': 'treegrid-overview.jsx', 'path': 'src/treegrid/treegrid-overview.jsx' }, { 'displayName': 'treegrid-overview.css', 'path': 'src/treegrid/treegrid-overview.css' }] },
  { 'path': 'treegrid/live-data', 'component': 'LiveStream', 'name': 'Live Data', 'description':'This demo for Essential JS 2 Tree Grid component shows how frequently the Grid cell is updated with real-time data.','order': '01', 'category': 'Tree Grid', 'api':'{"TreeGridComponent":["dataSource","enableVirtualization","enableVirtualMaskRow","enableHover", "columns", "rowHeight", "height", "allowSelection", "queryCellInfo", "load"]}' },
  { 'path': 'treegrid/default', 'component': 'Default', 'name': 'Default Functionalities', 'description':'This example shows how the Syncfusion React Tree Grid component looks with its default configuration.', 'order': '01', 'category': 'Tree Grid' ,'api':'{"TreeGridComponent":["dataSource", "treeColumnIndex", "height", "childMapping", "columns"] }'},
  { 'path': 'treegrid/adaptive', 'component': 'Adaptive', 'name': 'Adaptive Layout ', 'description':'This demo for Essential JS 2 Tree Grid control shows frozen columns feature of Tree Grid with Freeze direction Left/Right.', 'order': '01', 'category': 'Tree Grid' ,'api':'{"TreeGridComponent":["dataSource","childMapping","columns","treeColumnIndex","enableAdaptiveUI","allowFiltering","allowSorting","allowPaging"] }'},
  { 'path': 'treegrid/loading-animation', 'component': 'LoadingAnimation', 'name': 'Loading Animation', 'description':'This demo for Essential JS 2 Tree Grid component shows the loading indicator when Tree Grid loading and refreshing.', 'order': '01', 'category': 'Tree Grid', 'api':'{"TreeGridComponent":["columns", "dataSource","allowSorting","allowPaging", "allowFiltering", "loadingIndicator", "pageSettings"] }'},

  { 'path': 'treegrid/localdata', 'component': 'LocalData', 'name': 'Local Data', 'description':'This example shows the binding of an array of list objects in the Syncfusion React Tree Grid component.', 'order': '02', 'category': 'Data Binding' ,'api':'{"TreeGridComponent":["dataSource", "treeColumnIndex", "height", "childMapping", "columns"] }'},
  { 'path': 'treegrid/remote-data', 'component': 'RemoteData', 'name': 'Remote Data', 'description':'This example shows the binding of remote services by using the DataManager in the Syncfusion React Tree Grid.', 'order': '02', 'category': 'Data Binding' ,'api':'{"TreeGridComponent":["dataSource","allowPaging", "columns","treeColumnIndex", "hasChildMapping", "parentIdMapping","idMapping","height"] }'},
  { 'path': 'treegrid/selfreference', 'component': 'SelfReference', 'name': 'Self Reference Data', 'description':'This example illustrates binding self-referential flat data with parent ID to a Syncfusion React Tree Grid component.', 'order': '02', 'category': 'Data Binding' ,'api':'{"TreeGridComponent":["dataSource","allowPaging", "columns","treeColumnIndex","idMapping","parentIdMapping"] }'},

  { 'path': 'treegrid/columntemplate', 'component': 'ColumnTemplate', 'name': 'Column Template', 'description':'This demo explains how to define the template in Tree Grid columns in Syncfusion React Tree Grid component.', 'order': '03', 'category': 'Columns' ,'api':'{"TreeGridComponent":["dataSource","childMapping", "treeColumnIndex","width","height","columns","rowHeight"] }'},
  { 'path': 'treegrid/header-template', 'component': 'HeaderTemplate', 'name': 'Header Template', 'description':'This demo explains how to customize column headers to show additional HTML elements, such as icons, images, etc. in Syncfusion React Tree Grid component.', 'order': '03', 'category': 'Columns' ,'api':'{"TreeGridComponent":["dataSource", "childMapping", "treeColumnIndex","allowPaging","columns"] }'},
  { 'path': 'treegrid/columnformatting', 'component': 'ColumnFormat', 'name': 'Column Formatting', 'description':'This demo explains how to display the content of Tree Grid columns based on the specified format in Syncfusion React Tree Grid.', 'order': '03', 'category': 'Columns' ,'api':'{"TreeGridComponent":["dataSource","childMapping", "treeColumnIndex","columns","allowPaging"] }'},
  { 'path': 'treegrid/cellalignment', 'component': 'CellAlign', 'name': 'Cell Alignment', 'description':'This demo explains how to align the content inside the cells of Tree Grid columns and headers in Syncfusion React Tree Grid component.', 'order': '03', 'category': 'Columns' ,'api':'{"TreeGridComponent":["dataSource","childMapping","allowPaging","columns"] }'},
  { 'path': 'treegrid/reorder', 'component': 'Reorders', 'name': 'Reorder', 'description':'This demo explains how to reorder the columns of Tree Grid by simple drag and drop of columns using Syncfusion React Tree Grid component.', 'order': '03', 'category': 'Columns' ,'api':'{"TreeGridComponent":["dataSource","childMapping", "treeColumnIndex","allowReordering","actionComplete","columns","allowPaging"] }'},
  { 'path': 'treegrid/stacked-header', 'component': 'Stacked', 'name': 'Stacked Header', 'description':'This demo explains how to provide a common header for the group of columns in Syncfusion React Tree Grid component.', 'order': '03', 'category': 'Columns' ,'api':'{"TreeGridComponent":["dataSource","childMapping", "treeColumnIndex","allowPaging","pageSettings","columns"] }'},
  { 'path': 'treegrid/column-menu', 'component': 'TreeGridColumnMenu', 'name': 'Column Menu', 'description':'This demo explains the default functionalities of the Column Menu in Syncfusion React Tree Grid component.', 'order': '03', 'category': 'Columns' ,'api':'{"TreeGridComponent":["dataSource","childMapping","allowPaging","columns", "showColumnMenu"] }'},
  { 'path': 'treegrid/autowrap', 'component': 'AutoWrap', 'name': 'Auto Wrap Column Cells', 'description':'This demo explains how to wrap the content of columns within the specified width of Tree Grid columns in Syncfusion React Tree Grid component.', 'order': '03', 'category': 'Columns' ,'api':'{"TreeGridComponent":["dataSource", "childMapping", "treeColumnIndex","allowPaging","allowTextWrap","columns","pageSettings"] }'},
  { 'path': 'treegrid/column-chooser', 'component': 'TreeGridColumnChooser', 'name': 'Column Chooser', 'description':'This demo explains column chooser feature in Tree Grid columns in Syncfusion React Tree Grid component.', 'order': '03', 'category': 'Columns' ,'api':'{"TreeGridComponent":["dataSource","childMapping","treeColumnIndex","columns","allowPaging"] }'},
  { 'path': 'treegrid/showhidecolumn', 'component': 'ShowHideColumn', 'name': 'Show or Hide Column', 'description':'This demo explains how to hide or show the columns of Tree Grid dynamically using Syncfusion React Tree Grid methods.', 'order': '03', 'category': 'Columns' ,'api':'{"TreeGridComponent":["dataSource", "childMapping", "treeColumnIndex","allowPaging","allowTextWrap","columns","pageSettings"] }'},
  { 'path': 'treegrid/checkbox-column', 'component': 'CheckboxColumn', 'name': 'Checkbox Column', 'description':'This demo explains how the hierarchy selection between the records using column checkboxes in Syncfusion React Tree Grid component.', 'order': '03', 'category': 'Columns' ,'api':'{"TreeGridComponent":["dataSource","childMapping", "treeColumnIndex","allowPaging","pageSettings","columns"] }'},

  { 'path': 'treegrid/row-template', 'component': 'RowTemplate', 'name': 'Row Template', 'description':'This demo for Essential JS 2 Tree Grid control shows the usage of the row template feature. We have rendered each Tree Grid row using template.', 'order': '04', 'category': 'Rows' ,'api':'{"TreeGridComponent":["dataSource","childMapping", "treeColumnIndex","columns"] }'},
  { 'path': 'treegrid/detail-template', 'component': 'DetailTemplate', 'name': 'Detail Template', 'description':'This demo shows Tree Grid with detail template feature and also each row contains detailed information about a row.', 'order': '04', 'category': 'Rows' ,'api':'{"TreeGridComponent":["dataSource","childMapping", "treeColumnIndex","columns","height"] }'},
  { 'path': 'treegrid/drag-anddrop', 'component': 'DragAndDropBetween', 'name': 'Drag and Drop', 'description':'This demo for Essential JS 2 trTree Grideegrid control how the rows can be dragged between the Tree Grid using the row drag-and-drop feature.', 'order': '04', 'category': 'Rows' ,'api':'{"TreeGridComponent":["dataSource","childMapping", "treeColumnIndex","columns","allowPaging","pageSettings","allowRowDragAndDrop"] }'},
  { 'path': 'treegrid/drag-drop', 'component': 'DragAndDrop', 'name': 'Drag and Drop within Tree Grid', 'description':'This demo for Essential JS 2 trTree Grideegrid control how the rows can be dragged within the Tree Grid using the row drag-and-drop feature.', 'order': '04', 'category': 'Rows' ,'api':'{"TreeGridComponent":["dataSource","childMapping", "treeColumnIndex","columns"] }'},
  { 'path': 'treegrid/rowhover', 'component': 'RowHover', 'name': 'Row Hover', 'hideOnDevice': true, 'description':'This demo explains how the Tree Grid row color is changed while move the mouse over a row in Syncfusion React Tree Grid content.', 'order': '04', 'category': 'Rows' ,'api':'{"TreeGridComponent":["dataSource","childMapping", "treeColumnIndex","enableHover","columns"] }'},
  { 'path': 'treegrid/rowheight', 'component': 'RowHeight', 'name': 'Row Height', 'description':'This demo shows how to set different row height to the Tree Grid rows of Syncfusion React Tree Grid component.', 'order': '04', 'category': 'Rows' ,'api':'{"TreeGridComponent":["dataSource","childMapping", "treeColumnIndex","rowHeight","columns"] }'},

  { 'path': 'treegrid/inline-editing', 'component': 'Editing', 'name': 'Inline Editing', 'description':'This example shows how to add and edit Tree Grid row or Tree Grid cell inline on the Syncfusion React Tree Grid component.', 'order': '05', 'category': 'Editing' ,'api':'{"TreeGridComponent":["dataSource", "childMapping", "treeColumnIndex", "editSettings", "toolbar", "columns", "height"] }'},
  { 'path': 'treegrid/dialog-editing', 'component': 'Dialog', 'name': 'Dialog Editing', 'description':'This demo explains how to edit a Tree Grid record in the Dialog mode using Syncfusion React Tree Grid component.', 'order': '05', 'category': 'Editing' ,'api':'{"TreeGridComponent":["dataSource", "childMapping", "treeColumnIndex", "editSettings", "toolbar", "columns", "height"] }'},
  { 'path': 'treegrid/batch-edit', 'component': 'Batch', 'name': 'Batch Editing', 'description':'This example shows how to add and edit Tree Grid record in Batch mode using Syncfusion React Tree Grid component.', 'order': '05', 'category': 'Editing' ,'api':'{"TreeGridComponent":["dataSource", "childMapping", "treeColumnIndex", "editSettings", "toolbar", "columns", "height"] }'},
  { 'path': 'treegrid/commandcolumn', 'component': 'Command', 'name': 'Command Column', 'description':'This demo explains how to include CRUD action buttons as one of the columns in Syncfusion React Tree Grid component.', 'order': '05', 'category': 'Editing' ,'api':'{"TreeGridComponent":["dataSource", "childMapping", "treeColumnIndex", "editSettings", "toolbar", "columns", "height"] }'},
  { 'path': 'treegrid/celledittype', 'component': 'EditType', 'name': 'Cell Edit Type', 'description':'This demo explains how to set different edit types and how to define edit params for the Tree Grid columns in Syncfusion React Tree Grid component.', 'order': '05', 'category': 'Editing' ,'api':'{"TreeGridComponent":["dataSource", "childMapping", "treeColumnIndex", "editSettings", "toolbar", "columns", "height"] }'},
  { 'path': 'treegrid/edittemplate', 'component': 'EditTemplate', 'name': 'Edit Template', 'description':'This demo explains how create a custom editor control for the Tree Grid cells when a row is edited in Syncfusion React Tree Grid.', 'order': '05', 'category': 'Editing' ,'api':'{"TreeGridComponent":["dataSource", "childMapping", "treeColumnIndex", "editSettings", "toolbar", "columns", "height"] }'},
  { 'path': 'treegrid/lockrow', 'component': 'LockRow', 'name': 'Lock Row', 'description':'This demo explains how to disable editing for specific rows dynamically in Syncfusion React Tree Grid component.', 'order': '05', 'category': 'Editing' ,'api':'{"TreeGridComponent":["dataSource", "childMapping", "treeColumnIndex", "editSettings", "toolbar", "columns", "height"] }'},

  { 'path': 'treegrid/sorting', 'component': 'Sorting', 'name': 'Multi Sorting', 'description':'This demo demonstrates to sort multiple columns of Tree Grid by hold the CTRL key and click on the column headers of Syncfusion React Tree Grid component.', 'order': '06', 'category': 'Sorting' ,'api':'{"TreeGridComponent":["dataSource","childMapping", "treeColumnIndex","allowPaging","pageSettings","columns","allowSorting","actionComplete","sortSettings"] }'},
  { 'path': 'treegrid/sortingapi', 'component': 'SortingAPI', 'name': 'Sorting API', 'description':'This demo explains how to sort columns dynamically using methods of Syncfusion React Tree Grid component.', 'order': '06', 'category': 'Sorting' ,'api':'{"TreeGridComponent":["dataSource","childMapping", "treeColumnIndex","allowPaging","pageSettings","columns","allowSorting","actionComplete","sortSettings"] }'},

  { 'path': 'treegrid/filtering', 'component': 'Filtering', 'name': 'Default Filtering', 'description':'This demo explains the default functionalities of filtering and how to define the template for filter bar in Syncfusion React Tree Grid.', 'order': '07', 'category': 'Filtering' ,'api':'{"TreeGridComponent":["dataSource","childMapping","allowPaging","columns","allowFiltering","filterSettings","treeColumnIndex"] }'},
  { 'path': 'treegrid/filter-menu', 'component': 'FilterMenu', 'name': 'Menu Filter', 'description':'This demo explains how to filter the content using menu filter type of Syncfusion React Tree Grid component.', 'order': '07', 'category': 'Filtering' ,'api':'{"TreeGridComponent":["dataSource","childMapping","allowPaging","columns","allowFiltering","treeColumnIndex","filterSettings"] }'},
  { 'path': 'treegrid/searching', 'component': 'Search', 'name': 'Search', 'description':'This demo explains how to search the text entered in the search bar in Syncfusion React Tree Grid content.', 'order': '07', 'category': 'Filtering' ,'api':'{"TreeGridComponent":["dataSource","allowPaging","pageSettings","columns","childMapping", "treeColumnIndex","toolbar"] }'},

  { 'path': 'treegrid/paging', 'component': 'Paging', 'name': 'Pager Dropdown', 'description':'This demo explains how to display the records in paginated view in Syncfusion React Tree Grid component.', 'order': '08', 'category': 'Paging' ,'api':'{"TreeGridComponent":["dataSource","childMapping","allowPaging","columns","pageSettings","treeColumnIndex"] }'},
  { 'path': 'treegrid/pagingapi', 'component': 'PagingAPI', 'name': 'Paging API', 'description':'This demo explains how to customize a pager using the APIs that are relevant to paging of Syncfusion React Tree Grid component.', 'order': '08', 'category': 'Paging' ,'api':'{"TreeGridComponent":["dataSource","childMapping","allowPaging","columns","pageSettings","treeColumnIndex"] }'},

  { 'path': 'treegrid/defaultscrolling', 'component': 'DefaultScrolling', 'name': 'Default Scrolling', 'description':'This demo for Essential JS 2 Tree Grid control shows the usage of horizontal and vertical scrollbars to view Tree Grid content that exceeds the Tree Grid area.', 'order': '09', 'category': 'Scrolling' ,'api':'{"TreeGridComponent":["dataSource","childMapping","treeColumnIndex","height"] }'},
  { 'path': 'treegrid/frozencolumn', 'component': 'FrozenColumn', 'name': 'Frozen Columns', 'hideOnDevice': true, 'description':'This demo for Essential JS 2 Tree Grid control shows frozen columns feature of Tree Grid. Scroll the movable content to view the frozen columns.', 'order': '09', 'category': 'Scrolling' ,'api':'{"TreeGridComponent":["dataSource","childMapping","columns","treeColumnIndex","frozenColumns"] }'},
  { 'path': 'treegrid/frozen-api', 'component': 'FrozenAPI', 'name': 'Freeze Direction', 'description':'This demo for Essential JS 2 Tree Grid control shows frozen columns feature of Tree Grid with Freeze direction Left/Right.', 'order': '09', 'category': 'Scrolling' ,'api':'{"TreeGridComponent":["dataSource","childMapping","columns","treeColumnIndex","freeze"] }'},
  { 'path': 'treegrid/virtualscrolling', 'component': 'VirtualScrolling', 'name': 'Virtual Scrolling', 'description':'This demo demonstrates how to use Essential JS 2 Tree Grid to show a large data view without performance degradation by rendering only the required rows.', 'order': '09', 'category': 'Scrolling', 'api':'{"TreeGridComponent":["dataSource","childMapping","treeColumnIndex","height","enableVirtualization"] }'},
  { 'path': 'treegrid/infinitescrolling', 'component': 'InfiniteScrolling', 'name': 'Infinite Scrolling', 'description':'This demo demonstrates how to use Essential JS 2 Tree Grid to show a large data view without performance degradation by rendering only the required rows.', 'order': '09', 'category': 'Scrolling' ,'api':'{"TreeGridComponent":["dataSource","childMapping","treeColumnIndex","height","enableInfiniteScrolling"] }'},

  { 'path': 'treegrid/aggregate-default', 'component': 'AggregateRow', 'name': 'Default Aggregate', 'description':'This demo explains how to display the summary values such as average, minimum, etc., for the columns in Syncfusion React Tree Grid component.', 'order': '10', 'category': 'Aggregates' ,'api':'{"TreeGridComponent":["dataSource","childMapping","columns","aggregates", "treeColumnIndex", "toolbar", "toolbarClick", "allowPdfExport", "allowExcelExport"] }'},
  { 'path': 'treegrid/custom-aggregate', 'component': 'CustomAggregate', 'name': 'Custom Aggregate', 'description':'This demo explains how to display the custom aggregate for the columns in Syncfusion React Tree Grid component.', 'order': '10', 'category': 'Aggregates' ,'api':'{"TreeGridComponent":["dataSource","childMapping","columns","aggregates","treeColumnIndex"] }'},

  { 'path': 'treegrid/selection', 'component': 'Selection', 'name': 'Default Selection', 'description':'This demo explains the customization of selection mode and toggle selection of Syncfusion React Tree Grid component.', 'order': '11', 'category': 'Selection' ,'api':'{"TreeGridComponent":["dataSource","childMapping","allowPaging","columns","allowSelection","selectionSettings","treeColumnIndex"] }'},
  { 'path': 'treegrid/selectionapi', 'component': 'SelectionAPI', 'name': 'Selection API', 'description':'This demo explains how to select and clear multiple rows using methods of Syncfusion React Tree Grid component.', 'order': '11', 'category': 'Selection' ,'api':'{"TreeGridComponent":["dataSource","childMapping","allowPaging","columns","allowSelection","selectionSettings","treeColumnIndex"] }'},
  { 'path': 'treegrid/checkbox-selection', 'component': 'CheckboxSelection', 'name': 'Checkbox Selection', 'description':'This demo explains how the check box selection feature can be used to select Tree Grid rows in Syncfusion React Tree Grid component.', 'order': '11', 'category': 'Selection' ,'api':'{"TreeGridComponent":["dataSource","childMapping","allowPaging","columns","allowSelection","selectionSettings","treeColumnIndex"] }'},

  { 'path': 'treegrid/export', 'component': 'Export', 'name': 'Default Exporting', 'description':'This demo explains how to export the Tree Grid content to Excel, PDF, and CSV documents using the Syncfusion React Tree Grid component.', 'order': '12', 'category': 'Exporting' ,'api':'{"TreeGridComponent":["dataSource","childMapping", "treeColumnIndex","columns","toolbar"] }'},
  { 'path': 'treegrid/print', 'component': 'Print', 'name': 'Print', 'description':'This demo explains how to print the records of the Tree Grid using the Print feature of Syncfusion React Tree Grid component.', 'order': '12', 'category': 'Exporting' ,'api':'{"TreeGridComponent":["dataSource","childMapping", "treeColumnIndex","columns","toolbar"] }'},

  { 'path': 'treegrid/contextmenu', 'component': 'TreeContextMenu', 'name': 'Default Context Menu', 'description':'This demo explains the usage of context menu and the default context menu items in Syncfusion React Tree Grid component.', 'order': '13', 'category': 'Context Menu','api':'{"TreeGridComponent":["dataSource","childMapping", "treeColumnIndex","allowPaging","columns","allowSorting","contextMenu","sortSettings"] }'},
  { 'path': 'treegrid/customcontextmenu', 'component': 'CustomContextMenu', 'name': 'Custom Context Menu', 'description':'This demo explains the usage of custom context menu items of context menu in Syncfusion React Tree Grid component.', 'order': '13', 'category': 'Context Menu' ,'api':'{"TreeGridComponent":["dataSource","childMapping", "treeColumnIndex","allowPaging","columns","allowSorting","contextMenu","sortSettings"] }'},
  
  { 'path': 'treegrid/gridlines', 'component': 'GridLines', 'name': 'Gridlines', 'description':'This demo explains how to customize the grid lines in Tree Grid using Syncfusion React Tree Grid component.', 'order': '14', 'category': 'Miscellaneous' ,'api':'{"TreeGridComponent":["dataSource","childMapping", "treeColumnIndex","columns","gridLines"] }'},
  { 'path': 'treegrid/clipboard', 'component': 'Clipboard', 'name': 'Clipboard', 'description':'This example demonstrates copy to clipboard functionality of the Tree Grid component by selecting row and click copy button in toolbar', 'order': '14', 'category': 'Miscellaneous' ,'api':'{"TreeGridComponent":["dataSource", "treeColumnIndex", "allowPaging", "allowSelection", "childMapping", "columns", "copyHierarchyMode"] }'},
  { 'path': 'treegrid/conditionalformatting', 'component': 'Format', 'name': 'Conditional Formatting', 'description':'This demo explains how to apply styles to specific cells based on certain conditions in Syncfusion React Tree Grid component.', 'order': '14', 'category': 'Miscellaneous' ,'api':'{"TreeGridComponent":["dataSource","childMapping", "treeColumnIndex","columns"] }'},
  { 'path': 'treegrid/toolbar-template', 'component': 'ToolbarTemplate', 'name': 'Toolbar Template', 'description':'This demo explains how to render custom template elements in a toolbar by which any custom operation can be performed in Syncfusion React Tree Grid.', 'order': '14', 'category': 'Miscellaneous' ,'api':'{"TreeGridComponent":["dataSource","childMapping", "treeColumnIndex","columns","toolbar"] }'},
  { 'path': 'treegrid/events', 'component': 'Events', 'name': 'Events', 'description':'This demo explains the basic functionalities of the events that are available in the Syncfusion React Tree Grid component.', 'order': '14', 'category': 'Miscellaneous' ,'api':'{"TreeGridComponent":["dataSource","childMapping", "treeColumnIndex","columns","allowKeyboard"] }'},
  { 'path': 'treegrid/keyboard', 'component': 'KeyBoard', 'name': 'Keyboard Navigation', 'hideOnDevice': true, 'description':'This demo explains the key combinations used to perform corresponding Tree Grid actions in Syncfusion React Tree Grid component.', 'order': '14', 'category': 'Miscellaneous' ,'api':'{"TreeGridComponent":["dataSource","childMapping", "treeColumnIndex","columns","allowKeyboard"] }'}
]
