export const DropDownListSampleOrder:Object = [
    { 'path': 'drop-down-list/default', 'component':'Default', 'name': 'Default Functionalities', 'order': '01', 'category': 'DropDownList', 'api': '{"DropDownList": ["popupHeight", "placeholder", "index", "change"]}' },
    { 'path': 'drop-down-list/grouping-icon', 'component':'Grouping', 'name': 'Grouping and Icons', 'order': '01', 'category': 'DropDownList', 'api': '{"DropDownList": ["dataSource", "fields", "popupHeight", "placeholder"]}' },
    { 'path': 'drop-down-list/data-binding', 'component':'Data', 'name': 'Data Binding', 'order': '01', 'category': 'DropDownList', 'api': '{"DropDownList": ["dataSource", "fields", "query", "sortOrder", "autofill", "popupHeight", "placeholder"]}' },
    { 'path': 'drop-down-list/filtering', 'component':'Filtering', 'name': 'Filtering', 'order': '01', 'category': 'DropDownList', 'api': '{"DropDownList": ["dataSource", "fields", "allowFiltering", "filtering", "filterBarPlaceholder", "popupHeight", "placeholder"]}' },
    { 'path': 'drop-down-list/template', 'component':'Templates', 'name': 'Templates', 'order': '01', 'category': 'DropDownList', 'api': '{"DropDownList": ["dataSource", "fields","headerTemplate", "itemTemplate", "valueTemplate", "popupHeight", "placeholder"]}' },
    { 'path': 'drop-down-list/cascading', 'component':'Cascading', 'name': 'Cascading', 'order': '01', 'category': 'DropDownList', 'api': '{"DropDownList": ["dataSource", "fields", "change", "placeholder", "popupHeight", "value", "enabled"]}' },
    { 'path': 'drop-down-list/inline', 'component':'Inline', 'name': 'Inline', 'order': '01', 'category': 'DropDownList', 'api': '{"DropDownList": ["dataSource", "fields", "value"]}' },
    { 'path': 'drop-down-list/diacritics-filtering', 'component':'DiacriticsFiltering', 'name': 'Diacritics Filtering', 'order': '01', 'category': 'DropDownList', 'api': '{"DropDownList": ["dataSource", "ignoreAccent", "placeholder","allowFiltering"]}' }
]