export const DropDownListSampleOrder:Object = [
    { 'path': 'drop-down-list/default', 'component':'Default', 'name': 'Default Functionalities', 'description': 'This demo for Syncfusion vue drop-down list component shows the default rendering with minimum configuration.', 'order': '01', 'category': 'Dropdown List', 'api': '{"DropDownList": ["popupHeight", "placeholder", "index", "change"]}' },
    { 'path': 'drop-down-list/grouping-icon', 'component':'Grouping', 'name': 'Grouping and Icons', 'description': 'This demo shows the grouping based on different categories with individual header and icon support in the Syncfusion vue drop-down list component.', 'order': '01', 'category': 'Dropdown List', 'api': '{"DropDownList": ["dataSource", "fields", "popupHeight", "placeholder"]}' },
    { 'path': 'drop-down-list/data-binding', 'component':'Data', 'name': 'Data Binding', 'description': 'This demo for Syncfusion vue drop-down list component shows how to bind with  local data source and how to fetch data from remote data service.', 'order': '01', 'category': 'Dropdown List', 'api': '{"DropDownList": ["dataSource", "fields", "query", "sortOrder", "autofill", "popupHeight", "placeholder"]}' },
    { 'path': 'drop-down-list/filtering', 'component':'Filtering', 'name': 'Filtering', 'description': 'This demo explains the filtering functionalities of the Syncfusion vue drop-down list component.', 'order': '01', 'category': 'Dropdown List', 'api': '{"DropDownList": ["dataSource", "fields", "allowFiltering", "filtering", "filterBarPlaceholder", "popupHeight", "placeholder"]}' },
    { 'path': 'drop-down-list/template', 'component':'Templates', 'name': 'Templates', 'description': 'This demo explains on how to customize the appearance of each item in the pop-up list using template option in Syncfusion vue drop-down list component.', 'order': '01', 'category': 'Dropdown List', 'api': '{"DropDownList": ["dataSource", "fields","headerTemplate", "itemTemplate", "valueTemplate", "popupHeight", "placeholder"]}' },
    { 'path': 'drop-down-list/cascading', 'component':'Cascading', 'name': 'Cascading', 'description': 'This demo for Syncfusion vue drop-down list component shows the cascading support.', 'order': '01', 'category': 'Dropdown List', 'api': '{"DropDownList": ["dataSource", "fields", "change", "placeholder", "popupHeight", "value", "enabled"]}' },
    { 'path': 'drop-down-list/inline', 'component':'Inline', 'name': 'Inline', 'description': 'This demo for Syncfusion vue drop-down list component demonstrates to render the drop-down list component in line with other content.', 'order': '01', 'category': 'Dropdown List', 'api': '{"DropDownList": ["dataSource", "fields", "value"]}' },
    { 'path': 'drop-down-list/diacritics-filtering', 'component':'DiacriticsFiltering', 'name': 'Diacritics Filtering', 'description': 'This demo explains the diacritics filter functionality of the Syncfusion vue drop-down list component.', 'order': '01', 'category': 'Dropdown List', 'api': '{"DropDownList": ["dataSource", "ignoreAccent", "placeholder","allowFiltering"]}' }
]