export const GanttSampleOrder: Object = [
  { 'path': 'gantt/default', 'component': 'Default', 'name': 'Default Functionalities', 'order': '01', 'description':'This example demonstrates the simple Gantt chart with summary task, child tasks, milestone tasks, dependencies with event markers of project.', 'category': 'Gantt' ,'api':'{"GanttComponent":["dataSource","taskFields","height","highlightWeekends","eventMarkers","labelSettings"] }'},
  { 'path': 'gantt/remote-data', 'component': 'RemoteData', 'name': 'Remote Data', 'order': '01', 'description':'This sample demonstrates the way of binding data to Gantt chart with remote service. The Gantt chart data source is bound to remote data using DataManager.', 'category': 'Gantt' ,'api':'{"GanttComponent":["dataSource","height","taskFields","columns","treeColumnIndex","allowSelection","gridLines","highlightWeekends","timelineSettings","labelSettings","includeWeekend","projectStartDate","projectEndDate"]}'},
  { 'path': 'gantt/editing', 'component': 'Editing', 'name': 'Editing', 'order': '01', 'description':'This example demonstrates the cell editing, dialog editing, taskbar editing and dependency editing support in Gantt.', 'category': 'Gantt' ,'api':'{"GanttComponent":["dataSource","dateFormat","height","taskFields","editSettings","toolbar","columns","treeColumnIndex","allowSelection","gridLines","resourceNameMapping","resourceIDMapping","resources","highlightWeekends","timelineSettings","labelSettings","labelSettings","projectStartDate","projectEndDate"]}'},
  { 'path': 'gantt/filtering', 'component': 'Filtering', 'name': 'Filtering', 'order': '01', 'description':'This example demonstrates the filtering support with filter menu option for various types of columns in Gantt.', 'category': 'Gantt' ,'api':'{"GanttComponent":["dataSource","dateFormat","taskFields","columns","treeColumnIndex","height","timelineSettings","labelSettings","toolbar","allowFiltering","includeWeekend","timelineSettings","splitterSettings","durationUnit","dayWorkingTime","projectStartDate","projectEndDate"]}'},
  { 'path': 'gantt/timeline', 'component': 'Timeline', 'name': 'Timeline', 'order': '01', 'description':'This example demonstrates the various timeline mode options and properties available to customize the timeline in Gantt.', 'category': 'Gantt' ,'api':'{"GanttComponent":["dataSource","taskFields","treeColumnIndex","height","projectStartDate","projectEndDate","highlightWeekends","resourceNameMapping","resourceIDMapping","resources","timelineSettings","splitterSettings","treeColumnIndex","labelSettings","eventMarkers"]}'},
  { 'path': 'gantt/baseline', 'component': 'Baseline', 'name': 'Baseline', 'order': '01', 'description':'Baselines are enabled to view the deviation between the planned dates of tasks and actual progress of task dates.', 'category': 'Gantt' ,'api':'{"GanttComponent":["dataSource","renderBaseline","taskFields","columns","treeColumnIndex","allowSelection","includeWeekend","timelineSettings","tooltipSettings","durationUnit","dateFormat","dayWorkingTime","height","projectStartDate","projectEndDate"]}'},
  { 'path': 'gantt/taskbar-template', 'component': 'Taskbar', 'name': 'Taskbar Template', 'order': '01', 'description':'This example demonstrates the taskbar template support with child taskbar template, parent taskbar template and milestone template.', 'category': 'Gantt' ,'api':'{"GanttComponent":[ "dataSource","dateFormat","taskFields","columns","treeColumnIndex","rowHeight","taskbarHeight","dayWorkingTime","durationUnit","eventMarkers","height","taskbarTemplate","milestoneTemplate","projectStartDate","projectEndDate","timelineSettings","splitterSettings","labelSettings","tooltipSettings"]}'},
  { 'path': 'gantt/unscheduled-task', 'component': 'UnscheduledTask', 'name': 'Unscheduled Tasks', 'order': '01', 'description':'This example demonstrates the unscheduled tasks in Gantt with custom toolbar item and dynamic add support.', 'category': 'Gantt' ,'api':'{"GanttComponent":["dataSource","taskFields","editSettings","toolbar","height","labelSettings","allowUnscheduledTasks","timelineSettings","projectStartDate","projectEndDate","toolbarClick","splitterSettings","columns"]}'},
  { 'path': 'gantt/zooming', 'component': 'Zooming', 'name': 'Zooming', 'order': '01', 'description':'This example demonstrates the zooming support of the Gantt chart timeline and ZoomToFit support of the Gantt chart.', 'category': 'Gantt' ,'api':'{"GanttComponent":["dataSource","taskFields","toolbar","height","labelSettings","projectStartDate","projectEndDate"]}'},
  { 'path': 'gantt/context-menu', 'component': 'ContextMenuItem', 'name': 'Context Menu', 'order': '01', 'description':'This demo explains the usage of context menu and the default context menu items in Syncfusion Gantt control.', 'category': 'Gantt' ,'api':'{"GanttComponent":["dataSource","taskFields","toolbar","height","labelSettings","projectStartDate","projectEndDate"]}'},
  { 'path': 'gantt/exporting', 'component': 'Exporting', 'name': 'Exporting', 'order': '01', 'description': 'This demo explains how to export Gantt content to Excel and CSV documents using the Syncfusion TypeScript Gantt control.', 'category': 'Gantt', 'api': '{"GanttComponent":["dataSource","dateFormat","height","taskFields","toolbar","treeColumnIndex","allowSelection","allowExcelExport","gridLines","resourceNameMapping","resourceIDMapping","resources","highlightWeekends","timelineSettings","labelSettings","projectStartDate","projectEndDate"]}' }
]