/**
 * Election data for US
 */
//tslint:disable
export let electionData: Object[] = 
[
   { State: "Alabama", Candidate: "Trump", Trump:62.9,Clinton:34.6 },
    { State: "Alaska", Candidate: "Trump", Trump:52.9,Clinton:37.7},
    { State: "Arkansas", Candidate: "Trump", Trump:60.6,Clinton:33.7 },
    { State: "Arizona", Candidate: "Trump", Trump:49.5,Clinton:45.4 },
    { State: "California", Candidate: "Clinton", Trump:32.8,Clinton:61.6},
    { State: "Colorado", Candidate: "Clinton", Trump:47.3,Clinton:44.4 },
    { State: "Connecticut", Candidate: "Clinton", Trump:41.2,Clinton:54.5},
    { State: "Delaware", Candidate: "Clinton", Trump:53.4,Clinton:41.9 },
    { State: "District of Columbia",  Candidate: "Clinton", Trump:4.1,Clinton:92.8},
    { State: "Florida", Candidate: "Trump", Trump:49.1,Clinton:47.8 },
    { State: "Georgia", Candidate: "Trump", Trump:51.3,Clinton:45.6 },
    { State: "Hawaii", Candidate: "Clinton", Trump:62.2,Clinton:30 },
    { State: "Idaho", Candidate: "Trump", Trump:59.2,Clinton:27.6  },
    { State: "Illinois", Candidate: "Clinton", Trump:55.4,Clinton:39.4  },
    { State: "Indiana", Candidate: "Trump", Trump:57.2,Clinton:37.9  },
    { State: "Iowa", Candidate: "Trump", Trump:51.8,Clinton:42.2  },
    { State: "Kansas", Candidate: "Trump", Trump:57.2,Clinton:36.2 },
    { State: "Kentucky", Candidate: "Trump", Trump:62.5,Clinton:32.7  },
    { State: "Louisiana", Candidate: "Trump", Trump:58.1,Clinton:38.4  },
    { State: "Maine", Candidate: "Clinton", Trump:45.2,Clinton:47.9 },
    { State: "Maryland", Candidate: "Clinton", Trump:35.3,Clinton:60.5  },
    { State: "Massachusetts", Candidate: "Clinton", Trump:33.5,Clinton:60.8 },
    { State: "Michigan", Candidate: "Trump", Trump:47.6,Clinton:47.3  },
    { State: "Minnesota", Candidate: "Clinton", Trump:45.4,Clinton:46.9 },
    { State: "Mississippi", Candidate: "Trump", Trump:58.3,Clinton:39.7  },
    { State: "Missouri", Candidate: "Trump", Trump:57.1,Clinton:38.0  },
    { State: "Montana", Candidate: "Trump", Trump:56.5,Clinton:36.0 },
    { State: "Nebraska", Candidate: "Trump", Trump:60.3,Clinton:34.0  },
    { State: "Nevada", Candidate: "Clinton", Trump:45.5,Clinton:47.9  },
    { State: "New Hampshire", Candidate: "Clinton", Trump:47.2,Clinton:47.6  },
    { State: "New Jersey", Candidate: "Clinton", Trump:41.8,Clinton:55.0},
    { State: "New Mexico", Candidate: "Clinton", Trump:40.0,Clinton:48.3  },
    { State: "New York", Candidate: "Clinton", Trump:37.5,Clinton:58.8 },
    { State: "North Carolina", Candidate: "Trump", Trump:50.5,Clinton:46.7 },
    { State: "North Dakota", Candidate: "Trump", Trump:64.1,Clinton:27.8 },
    { State: "Ohio", Candidate: "Trump", Trump:52.1,Clinton:43.5 },
    { State: "Oklahoma", Candidate: "Trump", Trump:65.3,Clinton:28.9 },
    { State: "Oregon", Candidate: "Clinton", Trump:41.1,Clinton:51.7  },
    { State: "Pennsylvania", Candidate: "Trump", Trump:48.8,Clinton:47.6 },
    { State: "Rhode Island", Candidate: "Clinton", Trump:39.8,Clinton:55.4 },
    { State: "South Carolina", Candidate: "Trump", Trump:54.9,Clinton:40.8 },
    { State: "South Dakota", Candidate: "Trump", Trump:61.5,Clinton:31.7 },
    { State: "Tennessee", Candidate: "Trump", Trump:61.1,Clinton:34.9 },
    { State: "Texas", Candidate: "Trump", Trump:52.6,Clinton:43.4  },
    { State: "Utah", Candidate: "Trump", Trump:45.9,Clinton:27.8  },
    { State: "Vermont", Candidate: "Clinton", Trump:39.7,Clinton:61.1  },
    { State: "Virginia", Candidate: "Clinton", Trump:45.0,Clinton:49.9 },
    { State: "Washington", Candidate: "Clinton", Trump:4.1,Clinton:92.8  },
    { State: "Wisconsin", Candidate: "Trump", Trump:68.7,Clinton:26.5 },
    { State: "West Virginia", Candidate: "Trump", Trump:47.9,Clinton:46.9  },
    { State: "Wyoming", Candidate: "Trump", Trump:70.1,Clinton:22.5  }
   
    ];
    