export const SidebarSampleOrder = [
    { 'path': 'sidebar/default', 'component': 'Default', 'name': 'Default Functionalities', 'description': 'It demonstrates a simple, mobile-friendly and responsive Sidebar (Navigation drawer, Side Navigation menu) which navigates various parts of an application.', 'order': '01', 'category': 'Sidebar', 'api': '{ "SidebarComponent": ["type", "position", "showBackdrop", "closeOnDocumentClick", "change", "mediaQuery"]}',
        'sourceFiles': [{ 'displayName': 'default.tsx', 'path': 'src/sidebar/default.tsx' }, { 'displayName': 'default.jsx', 'path': 'src/sidebar/default.jsx' }, { 'displayName': 'sidebar-component.css', 'path': 'src/sidebar/sidebar-component.css' }] },
    { 'path': 'sidebar/docking-sidebar', 'component': 'Dock', 'name': 'Dock', 'description': 'This example demonstrates how the React Sidebar is docked to the main content when it is in closed state', 'order': '01', 'category': 'Sidebar', 'api': '{ "Sidebar": ["enableDock", "dockSize", "contextTo"]}',
        'sourceFiles': [{ 'displayName': 'docking-sidebar.tsx', 'path': 'src/sidebar/docking-sidebar.tsx' }, { 'displayName': 'docking-sidebar.jsx', 'path': 'src/sidebar/docking-sidebar.jsx' }, { 'displayName': 'dock.css', 'path': 'src/sidebar/dock.css' }] },
    { 'path': 'sidebar/api', 'component': 'API', 'name': 'API', 'description': 'It demonstrates how to change the behavior and appearance of sidebar in application through user friendly API’s like types, position, auto close and backdrop', 'order': '01', 'category': 'Sidebar', 'api': '{ "Sidebar": ["showBackdrop", "position", "types", "closeOnDocumentClick"] }',
        'sourceFiles': [{ 'displayName': 'api.tsx', 'path': 'src/sidebar/api.tsx' }, { 'displayName': 'api.jsx', 'path': 'src/sidebar/api.jsx' }, { 'displayName': 'api.css', 'path': 'src/sidebar/api.css' }] },
    { 'path': 'sidebar/sidebar-menu', 'component': 'SidebarWithMenu', 'name': 'Sidebar Menu', 'description': 'This example demonstrates how to render Menu for navigation purpose inside the React Sidebar of an application.', 'order': '01', 'category': 'Sidebar', 'api': '{ "Sidebar": ["width", "target","mediaQuery","dockSize","enableDock"] }',
        'sourceFiles': [{ 'displayName': 'sidebar-menu.tsx', 'path': 'src/sidebar/sidebar-menu.tsx' }, { 'displayName': 'sidebar-menu.jsx', 'path': 'src/sidebar/sidebar-menu.jsx' }, { 'displayName': 'sidebar-menu.css', 'path': 'src/sidebar/sidebar-menu.css' }] },
    { 'path': 'sidebar/responsive-panel', 'component': 'ResponsivePanel', 'name': 'Responsive Panel', 'description': 'This example demonstrates how to render responsive TreeView for navigation purpose inside the React Sidebar', 'order': '01', 'category': 'Sidebar', 'api': '{ "Sidebar": ["width", "target","mediaQuery"] }',
        'sourceFiles': [{ 'displayName': 'responsive-panel.tsx', 'path': 'src/sidebar/responsive-panel.tsx' }, { 'displayName': 'responsive-panel.jsx', 'path': 'src/sidebar/responsive-panel.jsx' }, { 'displayName': 'responsive-panel.css', 'path': 'src/sidebar/responsive-panel.css' }] },
    { 'path': 'sidebar/sidebar-list', 'component': 'SidebarWithList', 'name': 'Sidebar With ListView', 'description': 'This example demonstrates how the React Sidebar is integrated with a ListView to display a list of menu items', 'order': '01', 'category': 'Sidebar', 'api': '{ "Sidebar": ["open", "close"] }',
        'sourceFiles': [{ 'displayName': 'sidebar-list.tsx', 'path': 'src/sidebar/sidebar-list.tsx' }, { 'displayName': 'sidebar-list.jsx', 'path': 'src/sidebar/sidebar-list.jsx' }, { 'displayName': 'sidebar-list.css', 'path': 'src/sidebar/sidebar-list.css' }] }
];
