export const MultiSelectSampleOrder:Object = [
    { 'path': 'multi-select/default', 'component':'Default', 'name': 'Default Functionalities', 'description': 'This demo for Syncfusion vue multiselect component shows the default rendering with minimum configuration.', 'order': '01', 'category': 'MultiSelect Dropdown', 'api': '{"MultiSelect": ["mode", "placeholder"]}' },
    { 'path': 'multi-select/data-binding', 'component':'Data', 'name': 'Data Binding', 'description': 'This demo for Syncfusion vue multiselect component shows how to bind with  local data source and how to fetch data from remote data service.', 'order': '01', 'category': 'MultiSelect Dropdown', 'api': '{"MultiSelect": ["query", "dataSource", "fields", "sortOrder", "placeholder"]}' },
    { 'path': 'multi-select/grouping', 'component':'Grouping', 'name': 'Grouping', 'description': 'This demo shows the grouping based on different categories with individual header in the Syncfusion vue multiselect component.', 'order': '01', 'category': 'MultiSelect Dropdown', 'api': '{"MultiSelect": ["dataSource", "fields", "placeholder"]}' },
    { 'path': 'multi-select/template', 'component':'Templates', 'name': 'Templates', 'description': 'This demo shows on how to customize the appearance of each item in the pop-up list using template option in Syncfusion vue multiselect component.', 'order': '01', 'category': 'MultiSelect Dropdown', 'api': '{"MultiSelect": ["dataSource", "fields", "headerTemplate", "itemTemplate", "valueTemplate", "mode", "placeholder"]}' },
    { 'path': 'multi-select/filtering', 'component':'Filtering', 'name': 'Filtering',  'description': 'This demo explains the filtering functionalities of the Syncfusion vue multiselect component.', 'order': '01', 'category': 'MultiSelect Dropdown', 'api': '{"MultiSelect": ["query", "dataSource", "fields", "placeholder", "allowFiltering", "filtering"]}' },
    { 'path': 'multi-select/custom-value', 'component':'CustomTag', 'name': 'Custom Values', 'description': 'This demo for Syncfusion vue multiselect component demonstrates the addition of a new value that is not present in the predefined list.', 'order': '01', 'category': 'MultiSelect Dropdown', 'api': '{"MultiSelect": ["dataSource", "fields", "placeholder", "mode", "allowCustomValue"]}' },
    { 'path': 'multi-select/chip-customization', 'component':'ChipCustomization', 'name': 'Chip Customization', 'description': 'This demo for Syncfusion vue multiselect component demonstrates on how to customize the selected chip element when select.', 'order': '01', 'category': 'MultiSelect Dropdown', 'api': '{"MultiSelect": ["dataSource", "fields", "placeholder", "mode", "tagging"]}' },
    { 'path': 'multi-select/checkbox', 'component':'CheckBox', 'name': 'CheckBox', 'description': 'This demo for demonstrates the built-in support to select the multiple values through checkbox.', 'order': '01', 'category': 'MultiSelect Dropdown', 'api': '{"MultiSelect": ["dataSource", "fields", "placeholder"]}' },
    { 'path': 'multi-select/selection-limit', 'component':'SelectionLimit', 'name': 'Selection Limit', 'description': 'This demo for Syncfusion vue multiselect component demonstrates to limit the number of items that is selected in a component.', 'order': '01', 'category': 'MultiSelect Dropdown', 'api': '{"MultiSelect": ["dataSource", "fields", "placeholder", "maximumSelectionLength"]}' },
    { 'path': 'multi-select/diacritics-filtering', 'component':'DiacriticsFiltering', 'name': 'Diacritics Filtering', 'description': 'This demo explains the diacritics filter functionality of the Syncfusion vue multiselect component.', 'order': '01', 'category': 'MultiSelect Dropdown', 'api': '{"MultiSelect": ["dataSource", "ignoreAccent", "placeholder"]}' }
]