export const MultiSelectSampleOrder:Object = [
    { 'path': 'multi-select/default', 'component':'Default', 'name': 'Default Functionalities', 'order': '01', 'category': 'MultiSelect', 'api': '{"MultiSelect": ["mode", "placeholder"]}' },
    { 'path': 'multi-select/data-binding', 'component':'Data', 'name': 'Data Binding', 'order': '01', 'category': 'MultiSelect', 'api': '{"MultiSelect": ["query", "dataSource", "fields", "sortOrder", "placeholder"]}' },
    { 'path': 'multi-select/grouping', 'component':'Grouping', 'name': 'Grouping', 'order': '01', 'category': 'MultiSelect', 'api': '{"MultiSelect": ["dataSource", "fields", "placeholder"]}' },
    { 'path': 'multi-select/template', 'component':'Templates', 'name': 'Templates', 'order': '01', 'category': 'MultiSelect', 'api': '{"MultiSelect": ["dataSource", "fields", "headerTemplate", "itemTemplate", "valueTemplate", "mode", "placeholder"]}' },
    { 'path': 'multi-select/filtering', 'component':'Filtering', 'name': 'Filtering', 'order': '01', 'category': 'MultiSelect', 'api': '{"MultiSelect": ["query", "dataSource", "fields", "placeholder", "allowFiltering", "filtering"]}' },
    { 'path': 'multi-select/custom-value', 'component':'CustomTag', 'name': 'Custom Values', 'order': '01', 'category': 'MultiSelect', 'api': '{"MultiSelect": ["dataSource", "fields", "placeholder", "mode", "allowCustomValue"]}' },
    { 'path': 'multi-select/chip-customization', 'component':'ChipCustomization', 'name': 'Chip Customization', 'order': '01', 'category': 'MultiSelect', 'api': '{"MultiSelect": ["dataSource", "fields", "placeholder", "mode", "tagging"]}' },
    { 'path': 'multi-select/checkbox', 'component':'CheckBox', 'name': 'CheckBox', 'order': '01', 'category': 'MultiSelect', 'api': '{"MultiSelect": ["dataSource", "fields", "placeholder"]}' },
    { 'path': 'multi-select/selection-limit', 'component':'SelectionLimit', 'name': 'Selection Limit', 'order': '01', 'category': 'MultiSelect', 'api': '{"MultiSelect": ["dataSource", "fields", "placeholder", "maximumSelectionLength"]}' },
    { 'path': 'multi-select/diacritics-filtering', 'component':'DiacriticsFiltering', 'name': 'Diacritics Filtering', 'order': '01', 'category': 'MultiSelect', 'api': '{"MultiSelect": ["dataSource", "ignoreAccent", "placeholder"]}' }
]