export const RichTextEditorSampleOrder: Object = [
    { 'path': 'rich-text-editor/tools', 'component': 'Overview', 'name': 'Overview', 'description': 'This demo shows the overview of an HTML and markdown editor using Syncfusion react rich text editor component.', 'order': '01', 'category': 'RichTextEditor', 'api': '{"RichTextEditorComponent":["Inject","toolbarSettings","showCharCount","actionBegin","actionComplete","maxLength","appendTo"] }' },
    { 'path': 'rich-text-editor/rich-text-editor', 'component': 'Default', 'name': 'Default Functionalities', 'description': 'This demo for Syncfusion react component rich text editor component shows the default rendering with minimum configuration.', 'order': '01', 'category': 'RichTextEditor', 'api': '{"RichTextEditorComponent":["Inject","appendTo"] }' },
    { 'path': 'rich-text-editor/image', 'component': 'ImageSample', 'name': 'Image', 'description': 'This demo for Syncfusion react rich text editor component shows the option to insert images to your content with image caption and link URLs to images.', 'order': '01', 'category': 'RichTextEditor', 'api': '{"RichTextEditorComponent":["Inject","quickToolbarSettings","toolbarClick","appendTo","getRange"] }' },
    { 'path': 'rich-text-editor/inline', 'component': 'Inline', 'name': 'Inline', 'description': 'This demo Syncfusion react rich text editor component demonstrates on how to activate the editor on demand while editing the content.', 'order': '01', 'category': 'RichTextEditor', 'api': '{"RichTextEditorComponent":["Inject","inlineMode","toolbarSettings","format","fontFamily","appendTo","dataBind"] }' },
    { 'path': 'rich-text-editor/iframe', 'component': 'IFrame', 'name': 'IFrame', 'description': 'This demo Syncfusion react rich text editor component demonstrates the default rendering of the RichTextEditor in iframe mode.', 'order': '01', 'category': 'RichTextEditor', 'api': '{"RichTextEditorComponent":["Inject","height","iframeSettings","toolbarSettings","actionBegin","actionComplete","appendTo"] }' },
    { 'path': 'rich-text-editor/print', 'component': 'Print', 'name': 'Print', 'description': 'This demo for Syncfusion react rich text editor component shows how to print the content of the editor with its styles.', 'order': '01', 'category': 'RichTextEditor', 'api': '{"RichTextEditorComponent":["Inject","toolbarSettings","print","appendTo"] }' },
    { 'path': 'rich-text-editor/ajax-load', 'component': 'AjaxContent', 'name': 'Ajax Content', 'description': 'This demo Syncfusion react rich text editor component demonstrates how to load content to the editor from an external source using Ajax library.', 'order': '01', 'category': 'RichTextEditor', 'api': '{"RichTextEditorComponent":["Inject","value","appendTo"] }' },
    { 'path': 'rich-text-editor/api', 'component': 'RTEApi', 'name': 'API', 'order': '01', 'description': 'This demo shows the usage of API in Syncfusion react rich text editor component.', 'category': 'RichTextEditor', 'api': '{"RichTextEditorComponent":["Inject","showCharCount","maxLength","appendTo","readonly","enabled","enableHtmlEncode","value","getSelection","selectAll"] }' },
    { 'path': 'rich-text-editor/client-side-events', 'component': 'RTEEvents', 'name': 'Events', 'description': 'This demo for Syncfusion react rich text editor component shows the events that have been triggered during the RichTextEditor operations.', 'order': '01', 'category': 'RichTextEditor', 'api': '{"RichTextEditorComponent":["Inject","toolbarSettings","created","actionBegin","actionComplete","focus","blur","change","toolbarClick","appendTo"] }' },
    { 'path': 'rich-text-editor/blog-posting', 'component': 'Forums', 'name': 'Use Case', 'description': 'This demo for Syncfusion react rich text editor component demonstrates how to design forum application using RichTextEditor.', 'order': '01', 'category': 'RichTextEditor', 'api': '{"RichTextEditorComponent":["Inject","placeholder","value","dataBind","refresh","appendTo"] }' },
    { 'path': 'rich-text-editor/types', 'component': 'Type', 'name': 'Type', 'description': 'This demo for Syncfusion react rich text editor component demonstrates the different behavior of toolbar support in the RichTextEditor.', 'order': '02', 'category': 'Toolbar', 'api': '{"RichTextEditorComponent":["Inject","floatingToolbarOffset","toolbarSettings","actionBegin","actionComplete","dataBind","appendTo"] }' },
    { 'path': 'rich-text-editor/custom-toolbar', 'component': 'CustomTool', 'name': 'Custom Tool', 'description': 'This demo for Syncfusion react rich text editor component shows the users to add their commands to the toolbar along with the built-in commands.', 'order': '02', 'category': 'Toolbar', 'api': '{"RichTextEditorComponent":["Inject","toolbarSettings","value","created","appendTo"] }' },
    { 'path': 'rich-text-editor/markdown-editor', 'component': 'MarkDown', 'name': 'Overview', 'type': 'update', 'description': 'This demo for Syncfusion react rich text editor component shows the markdown editing in the RichTextEditor with complete features.', 'order': '03', 'category': 'Markdown Editor', 'api': '{"RichTextEditorComponent":["Inject","toolbarSettings","height","created","disableToolbarItem","enableToolbarItem","editorMode","appendTo"] }' },
    { 'path': 'rich-text-editor/markdown-editor-preview', 'component': 'Preview', 'name': 'Preview', 'description': 'This demo for Syncfusion react rich text editor component shows the users to switch between editing content and its visual preview in Markdown Editor.', 'order': '03', 'category': 'Markdown Editor', 'api': '{"RichTextEditorComponent":["Inject","toolbarSettings","height","created","disableToolbarItem","enableToolbarItem","editorMode","actionBegin","appendTo"] }' },
    { 'path': 'rich-text-editor/markdown-editor-custom-format', 'component': 'CustomFormat', 'name': 'Custom Format', 'description': 'This demo for Syncfusion react rich text editor component demonstrates on how to customize tags of markdown formatting in RichTextEditor.', 'order': '03', 'category': 'Markdown Editor', 'api': '{"RichTextEditorComponent":["Inject","toolbarSettings","height","created","disableToolbarItem","enableToolbarItem","editorMode","formatter","appendTo"] }' }
]
