export const DialogSampleOrder: Object = [
    { 'path': 'dialog/default', 'component':'DefaultFunctionalities', 'description': 'This sample demonstrates the default rendering of the dialog component, which supports modal and non-modal (modeless) behavior based on its interaction state.', 'name': 'Default Functionalities', 'order': '01', 'category': 'Dialog', 'api': '{"Dialog": [ "header", "content", "target", "showCloseIcon", "buttons", "animationSettings", "closeOnEscape", "width", "open", "close", "visible", "show", "hide" ]}' },
    { 'path': 'dialog/custom-dialog', 'component':'Basic', 'description': 'This sample demonstrates how to create custom dialogs such as alert dialogs, confirmation dialogs, and prompt dialogs using the Essential JS 2 dialog component.', 'name': 'Custom Dialogs', 'order': '01', 'category': 'Dialog', 'api': '{"Dialog": [ "header", "content", "target", "showCloseIcon", "buttons", "animationSettings", "closeOnEscape", "width", "open", "close", "visible", "show", "hide"]}' },
    { 'path': 'dialog/modal-dialog', 'component':'Modal', 'description': 'This sample demonstrates the modal pop-up behavior of the dialog component, which helps display critical information such as errors and warnings.', 'name': 'Modal', 'order': '01', 'category': 'Dialog', 'api': '{"Dialog": [ "header", "content", "target", "showCloseIcon", "buttons", "animationSettings", "isModal", "width", "open", "close", "show", "hide", "overlayClick"]}' },
    { 'path': 'dialog/template', 'component':'Template', 'description': 'This sample demonstrates how to customize user interface elements like the header, footer, and content of the dialog component using a template.', 'name': 'Template', 'order': '01', 'category': 'Dialog', 'api': '{"Dialog": [ "header", "content", "target", "showCloseIcon", "buttons", "animationSettings", "isModal", "width", "open", "close", "show", "hide"]}' },
    { 'path': 'dialog/dialog-contents-via-ajax', 'description': 'This sample demonstrates how to load the content of the dialog component from external sources such as a file or website using the Essential JS 2 Ajax library.', 'component':'AjaxContent', 'name': 'Ajax Content', 'order': '01', 'category': 'Dialog', 'api': '{"Dialog": [ "header", "content", "target", "showCloseIcon", "buttons", "animationSettings", "width", "open", "close", "show"]}' },
    { 'path': 'dialog/draggable', 'type': 'update', 'description': 'This sample shows how to enable drag-and-drop actions in the dialog component to help reposition the dialog efficiently.', 'component':'Draggable', 'name': 'Draggable', 'order': '01', 'category': 'Dialog', 'api': '{"Dialog": [ "header", "content", "target", "showCloseIcon", "buttons", "animationSettings", "width", "open", "close", "closeOnEscape"]}' },
    { 'path': 'dialog/position', 'description': 'This sample demonstrates how to display the dialog component at various built-in and custom positions.', 'component':'Positioning', 'name': 'Positioning', 'order': '01', 'category': 'Dialog', 'api': '{"Dialog": [ "header", "content", "target", "showCloseIcon", "buttons", "animationSettings", "width", "open", "close", "closeOnEscape", "position"]}' },
    { 'path': 'dialog/animation', 'description': 'This sample demonstrates how to open or close the dialog with various animation effects, and how to customize the animation duration and delay.', 'component':'Animation', 'name': 'Animation', 'order': '01', 'category': 'Dialog', 'api': '{"Dialog": [ "header", "content", "target", "showCloseIcon", "buttons", "animationSettings", "width", "open", "close", "closeOnEscape"]}' },
    { 'path': 'dialog/multiple-dialogs', 'description': 'This sample demonstrates how to display multiple dialogs sequentially and how to open multiple dialogs simultaneously for both modal and modeless dialogs.', 'component':'MultipleDialogs', 'name': 'Multiple Dialogs', 'order': '01', 'category': 'Dialog', 'api': '{"Dialog": [ "header", "content", "target", "showCloseIcon", "buttons", "animationSettings", "width", "open", "close", "closeOnEscape"]}' }

]