export const SpreadsheetSampleOrder: Object = [
    { 'path': 'spreadsheet/default', 'component': 'Default', 'name': 'Default Functionalities', 'order': '01', 'category': 'Spreadsheet', 'api': '{"SpreadsheetComponent":[ "sheets", "openUrl","saveUrl","created" ] }', 'description': 'This example demonstrates the default functionalities of the Syncfusion React Spreadsheet that includes editing, importing & exporting.' },
    { 'path': 'spreadsheet/formula', 'component': 'Formula', 'name': 'Formula', 'order': '01', 'category': 'Spreadsheet', 'api': '{"SpreadsheetComponent":["sheets","showRibbon","definedNames","created" ] }', 'description': 'This demo for Essential JS 2 Spreadsheet control shows the way of using basic formulas with minimum configuration.' },
    { 'path': 'spreadsheet/protect-sheet', 'component': 'ProtectSheet', 'name': 'Protection', 'order': '01', 'category': 'Spreadsheet', 'api': '{"SpreadsheetComponent":["sheets","beforeCellRender","created" ] }', 'description': 'This demo for Essential JS 2 Spreadsheet control includes lock cell and protect sheet feature with its configurations.' },
    { 'path': 'spreadsheet/freeze-pane', 'component': 'FreezePane', 'name': 'Freeze Panes', 'order': '01', 'category': 'Spreadsheet', 'api': '{"sheets": [ "frozenRows", "frozenColumns"] }', 'description': 'This example demonstrates the default functionalities of the Syncfusion React Spreadsheet that includes freeze rows and columns feature.' },
    { 'path': 'spreadsheet/data-validation', 'component': 'DataValidation', 'name': 'Data Validation', 'order': '01', 'category': 'Spreadsheet', 'api': '{"sheets": ["columns", "rows", "name"], "rows": ["cells", "index"],"cells": ["value", "style"]}', 'description': 'This example demonstrates the default functionalities of the Syncfusion React Spreadsheet that includes data validation feature.' },
    { 'path': 'spreadsheet/hyperlink', 'component': 'Hyperlink', 'name': 'Hyperlink', 'order': '01', 'category': 'Spreadsheet', 'api': '{"sheets": ["columns", "rows", "name"], "rows": ["cells", "index"],"cells": ["value", "style"]}', 'description': 'This example demonstrates the default functionalities of the Syncfusion React Spreadsheet that includes hyperlink feature.' },
    { 'path': 'spreadsheet/cell-data-binding', 'component': 'CellDataBinding', 'name': 'Cell Data Binding', 'order': '02', 'category': 'Data Binding', 'api': '{"SpreadsheetComponent":["sheets","showFormulaBar","showRibbon" ] }', 'description': 'This demo for Essential React Spreadsheet control shows the cell data binding feature with minimum configuration.' },
    { 'path': 'spreadsheet/remote-data-binding', 'component': 'RemoteDataBinding', 'name': 'Remote Data Binding', 'order': '02', 'category': 'Data Binding', 'api': '{"SpreadsheetComponent":["sheets","showFormulaBar","showRibbon" ] }', 'description': 'This demo for Essential React Spreadsheet control shows the way of data binding with remote service using DataManager.' },
    { 'path': 'spreadsheet/cell-formatting', 'component': 'CellFormatting', 'name': 'Cell Formatting', 'order': '03', 'category': 'Formatting', 'api': '{"sheets": ["columns", "rows", "name"], "rows": ["cells", "index"],"cells": ["value", "style"]}', 'description': 'This demo for Essential JS 2 Spreadsheet control shows the  cell formatting feature and its customizations.' },
    { 'path': 'spreadsheet/number-formatting', 'component': 'NumberFormatting', 'name': 'Number Formatting', 'order': '03', 'category': 'Formatting', 'api': '{"sheets": ["columns", "rows", "name", "selectedRange"], "rows": ["cells"],"cells": ["value", "formatCode"],"range":["dataSource","startCell"]}', 'description': 'This demo for Essential JS 2 Spreadsheet control shows the way of number formatting with minimum configuration.' },
    { 'path': 'spreadsheet/conditional-formatting', 'component': 'ConditionalFormatting', 'name': 'Conditional Formatting', 'order': '03', 'category': 'Formatting', 'api': '{"SpreadsheetComponent":["sheets","created" ] }', 'description': 'This example demonstrates about the conditional formatting features like highlight cell rules, data bars,color scales, and icon sets.' },
    { 'path': 'spreadsheet/sorting-and-filtering', 'component': 'SortingAndFiltering', 'name': 'Sorting and Filtering', 'order': '04', 'category': 'Data Analysis', 'api': '{"SpreadsheetComponent":["sheets","showFieldAsHeader","created" ] }', 'description': 'This demo for Essential JS 2 Spreadsheet control shows sorting and filtering feature in ascending and descending order.' },
    { 'path': 'spreadsheet/chart', 'component': 'Chart', 'name': 'Chart', 'order': '05', 'category': 'Data Visualization', 'api': '{"SpreadsheetComponent":["sheets","openUrl","saveUrl","created" ] }', 'description': 'This sample visualizes the data using chart feature by comparing the GDP of different countries with various years' },
    { 'path': 'spreadsheet/image', 'component': 'Image', 'name': 'Image', 'order': '06', 'category': 'Illustrations', 'api': '{"SpreadsheetComponent":["sheets","showRibbon","showFormulaBar","created" ] }', 'description': 'This demo for Essential JS 2 Spreadsheet control shows image feature by using weekly Diet planner details.' },
    { 'path': 'spreadsheet/cell-template', 'component': 'CellTemplate', 'name': 'Cell Template', 'order': '07', 'category': 'Templates', 'api': '{"SpreadsheetComponent":["sheets","showFieldAsHeader","created" ] }', 'description': 'This demo for Essential JS 2 Spreadsheet control shows cell template featurewith input components like TextBox, DropDownList,RadioButton, MultiSelect etc.' }
];
