export const QueryBuilderSampleOrder: Object = [
    { 'path': 'query-builder/default', 'component': 'Default', 'name': 'Default Functionalities', 'order': '01', 'category': 'Query Builder', 'api': '{"QueryBuilderComponent":["width","dataSource", "columns", "rule", "created"]  }', 'description': 'This sample demonstrates the Query Builder component showing how to import and export a query in JSON format.', 'ftName': 'query-builder' },
    { 'path': 'query-builder/complex-databinding', 'component': 'ComplexDatabinding', 'name': 'Complex Databinding', 'order': '01', 'category': 'Query Builder', 'api': '{"QueryBuilderComponent":["width","columns", "rule", "fieldMode"]  }', 'description': 'This sample demonstrates the Complex Databinding with integration of DropdownTree functionalities of the Query Builder component', 'ftName': 'query-builder' },
    { 'path': 'query-builder/grid', 'component': 'DataGrid', 'name': 'Integration with Data Grid', 'order': '01', 'category': 'Query Builder', 'api': '{"QueryBuilderComponent":["width","dataSource", "columns", "rule", "ruleChange"]  }', 'description': 'This sample demonstrates the integration of Grid component to showcase the data population based on the created filters using Query Builder component.', 'ftName': 'query-builder' },
    { 'path': 'query-builder/mongo-sql', 'component': 'MongoSQL', 'name': 'Mongo and SQL Query', 'order': '01', 'category': 'Query Builder', 'api': '{"QueryBuilderComponent":["width","columns", "rule", "template", "ruleChange"] }', 'description': 'This sample demonstrates the Query Builder component by showing different types of queries such as SQL and MongoDB.', 'ftName': 'query-builder' },
    { 'path': 'query-builder/lock-group', 'component': 'LockGroup', 'name': 'Lock Group/Rule', 'order': '01', 'category': 'Query Builder', 'api': '{"QueryBuilderComponent":["width","columns", "rule", "template", "ruleChange"] }', 'description': 'This sample demonstrates the lock support of the Query Builder component. Click the lock button to lock the group or rule.', 'ftName': 'query-builder' },
    { 'path': 'query-builder/clone-group', 'component': 'CloneGroup', 'name': 'Clone Group/Rule', 'order': '01', 'category': 'Query Builder', 'api': '{"QueryBuilderComponent":["width","columns", "rule", "template", "ruleChange"] }', 'description': 'This sample demonstrates the clone support of the Query Builder component. Click the clone button to clone the group or rule.', 'ftName': 'query-builder' },
    { 'path': 'query-builder/drag-drop', 'component': 'DragDrop', 'name': 'Drag and Drop', 'order': '01', 'category': 'Query Builder', 'api': '{"QueryBuilderComponent":["width","columns", "rule", "template", "ruleChange"] }', 'description': 'This sample demonstrates the Drag Drop support of the Query Builder component. Click the lock button to lock the group or rule.', 'ftName': 'query-builder' },
    { 'path': 'query-builder/separate-connector', 'component': 'SeparateConnector', 'name': 'Separate Connector', 'order': '01', 'category': 'Query Builder', 'api': '{"QueryBuilderComponent":["width","columns", "rule", "template", "ruleChange"] }', 'description': 'This sample demonstrates the Drag Drop support of the Query Builder component. Click the lock button to lock the group or rule.', 'ftName': 'query-builder' },
    { 'path': 'query-builder/template', 'component': 'Template', 'name': 'Value Template', 'order': '02', 'category': 'Template', 'api': '{"QueryBuilderComponent":["width","columns", "rule", "ruleChange"]  }', 'description': 'This sample demonstrates the integration of the Dropdown List and Slider components as templates in the Query Builder component.', 'ftName': 'query-builder',
        'sourceFiles': [{ 'displayName': 'template.tsx', 'path': 'src/query-builder/template.tsx' }, { 'displayName': 'template.jsx', 'path': 'src/query-builder/template.jsx' }, { 'displayName': 'util.ts', 'path': 'src/query-builder/util.ts' }] },
    { 'path': 'query-builder/rule-template', 'component': 'RuleTemplate', 'name': 'Rule Template', 'order': '02', 'category': 'Template', 'api': '{"QueryBuilderComponent":["width","columns", "rule"]  }', 'description': 'This sample demonstrates the integration of DropdownList, ruleTemplate in the Query Builder component.', 'ftName': 'query-builder' },
    { 'path': 'query-builder/header-template', 'component': 'HeaderTemplate', 'name': 'Header Template', 'order': '02', 'category': 'Template', 'api': '{"QueryBuilderComponent":["width","columns", "rule", "headerTemplate"]  }', 'description': 'This sample demonstrates the integration of DropdownList, headerTemplate in the Query Builder component.', 'ftName': 'query-builder' }
]
