export const QueryBuilderSampleOrder: Object = [
    { 'path': 'query-builder/default', 'component': 'Default', 'name': 'Default Functionalities', 'order': '01', 'category': 'Query Builder', 'api': '{"QueryBuilderComponent":["width","dataSource", "columns", "rule", "created"]  }', 'description': 'This sample demonstrates the default functionalities of the Query Builder component. Click the plus button to add group or conditions.', 'ftName': 'query-builder' },
    { 'path': 'query-builder/complex-databinding', 'component': 'ComplexDatabinding', 'name': 'Complex Databinding', 'order': '01', 'category': 'Query Builder', 'api': '{"QueryBuilderComponent":["width","columns", "rule", "fieldMode"]  }', 'description': 'This sample demonstrates the Complex Databinding with integration of DropdownTree functionalities of the Query Builder component', 'ftName': 'query-builder' },
    { 'path': 'query-builder/grid', 'component': 'DataGrid', 'name': 'Integration with Data Grid', 'order': '01', 'category': 'Query Builder', 'api': '{"QueryBuilderComponent":["width","dataSource", "columns", "rule", "ruleChange"]  }', 'description': 'This sample demonstrates the integration of Grid component to showcase the data population based on the created filters using Query Builder component.', 'ftName': 'query-builder' },
    { 'path': 'query-builder/query-preview', 'component': 'QueryPreview', 'type': 'new', 'name': 'Query Preview', 'order': '01', 'category': 'Query Builder', 'api': '{"QueryBuilderComponent":["width","columns", "rule", "template", "ruleChange"] }', 'description': 'This sample demonstrates the Query Builder component with previewing queries in SQL, JSON, CEL, SpEL, and Mongo.', 'ftName': 'query-builder',
        'sourceFiles': [{ 'displayName': 'query-preview.tsx', 'path': 'src/query-builder/query-preview.tsx' }, { 'displayName': 'query-preview.jsx', 'path': 'src/query-builder/query-preview.jsx' }, { 'displayName': 'util.ts', 'path': 'src/query-builder/util.ts' }] },
    { 'path': 'query-builder/template', 'component': 'Template', 'name': 'Value Template', 'order': '02', 'category': 'Template', 'api': '{"QueryBuilderComponent":["width","columns", "rule", "ruleChange"]  }', 'description': 'This sample demonstrates the integration of DropdownList, Slider controls as Templates in the Query Builder component.', 'ftName': 'query-builder' },
    { 'path': 'query-builder/rule-template', 'component': 'RuleTemplate', 'name': 'Rule Template', 'order': '02', 'category': 'Template', 'api': '{"QueryBuilderComponent":["width","columns", "rule"]  }', 'description': 'This sample demonstrates the integration of DropdownList, ruleTemplate in the Query Builder component.', 'ftName': 'query-builder' },
    { 'path': 'query-builder/header-template', 'component': 'HeaderTemplate', 'name': 'Header Template', 'order': '02', 'category': 'Template', 'api': '{"QueryBuilderComponent":["width","columns", "rule", "headerTemplate"]  }', 'description': 'This sample demonstrates the integration of DropdownList, headerTemplate in the Query Builder component.', 'ftName': 'query-builder' }
]