export const StockChartSampleOrder: Object = [
    { 'path': 'stock-chart/default', 'component': 'Default', 'name': 'Default', 'order': '01', 'category': 'Stock Chart',
    'description': 'This demo for Essential JS2 Stock Chart control shows the default rendering of Stock chart with candle series.' },
    { 'path': 'stock-chart/ohlc', 'component': 'OHLC', 'name': 'OHLC', 'order': '01', 'category': 'Stock Chart',
    'description': 'This demo for Essential JS2 Stock Chart control shows the default rendering of Stock with Hilo Open Close series.' },
    { 'path': 'stock-chart/multi-pane', 'component': 'MultiPane', 'name': 'Candlestick and volume', 'order': '01', 'category': 'Stock Chart',
    'description': 'This demo for Essential JS2 Stock Chart control shows the default rendering of Stock with candle series.' },
    { 'path': 'stock-chart/multiple-series', 'component': 'MultipleSeries', 'name': 'Multiple Series', 'order': '01', 'category': 'Stock Chart',
    'description': 'This demo for Essential JS2 Stock Chart control shows the default rendering of Stock with multiple series.' },
    { 'path': 'stock-chart/spline', 'component': 'Spline', 'name': 'Spline', 'order': '01', 'category': 'Stock Chart',
    'description': 'This demo for Essential JS2 Stock Chart control shows the default rendering of Stock with Spline series.' },
    { 'path': 'stock-chart/area', 'component': 'Area', 'name': 'Area', 'order': '01', 'category': 'Stock Chart',
    'description': 'This demo for Essential JS2 Stock Chart control shows the default rendering of Stock with Area series.' },
    { 'path': 'stock-chart/spline-area', 'component': 'SplineArea', 'name': 'Spline Area', 'order': '01', 'category': 'Stock Chart', 'type':'update',
    'description': 'This demo for Essential JS2 Stock Chart control shows the default rendering of Stock with Spline Area series.' },
    { 'path': 'stock-chart/inversed-area', 'component': 'InversedArea', 'name': 'Inversed Area', 'order': '01', 'category': 'Stock Chart',
    'description': 'This demo for Essential JS2 Stock Chart control shows the default rendering of Stock with Area series inverted.' },
    { 'path': 'stock-chart/plot-line', 'component': 'PlotLine', 'name': 'Plot lines', 'order': '01', 'category': 'Stock Chart',
    'description': 'This demo for Essential JS2 Stock Chart control shows the default rendering of Stock with Spline Area series.' },
    { 'path': 'stock-chart/strip-line', 'component': 'StripLines', 'name': 'Plot band', 'order': '01', 'category': 'Stock Chart',
    'description': 'This demo for Essential JS2 Stock Chart control shows the default rendering of Stock with strip line.' },
    { 'path': 'stock-chart/period-customization', 'component': 'PeroidCustomization', 'name': 'Intraday', 'order': '01', 'category': 'Stock Chart',
    'description': 'This demo for Essential JS2 Stock Chart control shows the default rendering of Stock with period customization.'},
    { 'path': 'stock-chart/disabled-navigator', 'component': 'Navigator', 'name': 'Hide Range Selector', 'order': '01', 'category': 'Stock Chart',
    'description': 'This demo for Essential JS2 Stock Chart control shows the default rendering of Stock with range customization.' },
    { 'path': 'stock-chart/disabled-period', 'component': 'PeriodSelector', 'name': 'Hide Period Selector', 'order': '01', 'category': 'Stock Chart',
    'description': 'This demo for Essential JS2 Stock Chart control shows the default rendering of Stock with period customization.' },
    { 'path': 'stock-chart/datetime-category', 'component': 'DatetimeCategoryAxis', 'name': 'DateTime Category Axis', 'order': '01', 'category': 'Stock Chart',
    'description': 'This demo for Essential JS2 Stock Chart control shows the default rendering of Stock with DateTime Category Axis.' },
    { 'path': 'stock-chart/stock-events', 'component': 'StockEvents', 'name': 'Stock Events', 'order': '01', 'category': 'Stock Chart',
    'description': 'This demo for Essential JS2 Stock Chart control shows the default rendering of Stock with stock events.' }
]
