export const AutoCompleteSampleOrder:Object = [
    { 'path': 'auto-complete/default', 'component':'Default', 'name': 'Default Functionalities', 'description': 'This demo for Syncfusion vue autocomplete component shows the default rendering with minimum configuration.', 'order': '01', 'category': 'AutoComplete', 'api': '{"AutoComplete": ["dataSource", "value", "placeholder"]}' },
    { 'path': 'auto-complete/grouping-icon', 'component':'Grouping', 'name': 'Grouping and Icons', 'description': 'This demo shows the grouping based on different categories with individual header and icon support in the Syncfusion vue autocomplete component.', 'order': '01', 'category': 'AutoComplete', 'api': '{"AutoComplete": ["fields", "placeholder"]}' },
    { 'path': 'auto-complete/data-binding', 'component':'Data', 'name': 'Data Binding', 'description': 'This demo for Syncfusion vue autocomplete component shows how to bind with  local data source and how to fetch data from remote data service.', 'order': '01', 'category': 'AutoComplete', 'api': '{"AutoComplete": ["dataSource", "suggestionCount", "query", "sortOrder", "autofill", "filterType", "change"]}' },
    { 'path': 'auto-complete/template', 'component':'Templates', 'name': 'Templates', 'description': 'This demo for Syncfusion vue autocomplete component shows how to customize the appearance of each item in the pop-up list using template option.', 'order': '01', 'category': 'AutoComplete', 'api': '{"AutoComplete": ["dataSource", "fields", "headerTemplate", "itemTemplate", "placeholder", "popupHeight"]}' },
    { 'path': 'auto-complete/highlight', 'component':'Highlight', 'name': 'Highlight', 'description': 'This demo for Syncfusion vue autocomplete component explains the built-in support to highlight the searched characters in the suggested list items.', 'order': '01', 'category': 'AutoComplete', 'api': '{"AutoComplete": ["dataSource", "fields", "highlight", "placeholder"]}' },
    { 'path': 'auto-complete/custom-filtering', 'component':'CustomFiltering', 'name': 'Custom Filtering', 'description': 'This demo explains the custom filtering functionalities of the Syncfusion vue autocomplete component.', 'order': '01', 'category': 'AutoComplete', 'api': '{"AutoComplete": ["dataSource", "filtering", "fields", "placeholder"]}' },
    { 'path': 'auto-complete/diacritics-filtering', 'component':'DiacriticsFiltering', 'name': 'Diacritics Filtering', 'description': 'This demo explains the diacritics filter functionality of the Syncfusion vue autocomplete component.', 'order': '01', 'category': 'AutoComplete', 'api': '{"AutoComplete": ["dataSource", "ignoreAccent", "placeholder"]}' }
]
