export const ChartSampleOrder:Object = [
    { 'path': 'chart/line', 'component':'Line', 'name': 'Line', 'order': '01', 'category': 'Line Charts' },
    { 'path': 'chart/spline', 'component':'Spline', 'name': 'Spline', 'order': '01', 'category': 'Line Charts' },
    { 'path': 'chart/stepline', 'component':'StepLine', 'name': 'Step Line', 'order': '01', 'category': 'Line Charts' },
    { 'path': 'chart/dashed-line', 'component':'DashedLine', 'name': 'Dashed Line', 'order': '01', 'category': 'Line Charts' },
    { 'path': 'chart/spline-inversed', 'component':'SplineInversed', 'name': 'Inversed Spline', 'order': '01', 'category': 'Line Charts' },
    { 'path': 'chart/area', 'component':'Area', 'name': 'Area', 'order': '02', 'category': 'Area Charts' },
    { 'path': 'chart/steparea', 'component':'StepArea', 'name': 'Step Area', 'order': '02', 'category': 'Area Charts' },
    { 'path': 'chart/stacked-area', 'component':'StackedArea', 'name': 'Stacked Area', 'order': '02', 'category': 'Area Charts' },
    { 'path': 'chart/stacked-area100', 'component':'StackedArea100', 'name': '100% Stacked Area', 'order': '02', 'category': 'Area Charts' },
    { 'path': 'chart/area-empty', 'component':'AreaEmpty', 'name': 'Area - Empty Points', 'order': '02', 'category': 'Area Charts' },
    { 'path': 'chart/column', 'component':'Column', 'name': 'Column', 'order': '03', 'category': 'Bar Charts' },
    { 'path': 'chart/rounded-column', 'component':'RoundedColumn', 'name': 'Rounded Column', 'order': '03', 'category': 'Bar Charts' },
    { 'path': 'chart/column-placement', 'component':'ColumnPlacement', 'name': 'Back to Back Column', 'order': '03', 'category': 'Bar Charts' },
    { 'path': 'chart/bar', 'component':'Bar', 'name': 'Bar', 'order': '03', 'category': 'Bar Charts' },
    { 'path': 'chart/stacked-column', 'component':'StackedColumn', 'name': 'Stacked Column', 'order': '03', 'category': 'Bar Charts' },
    { 'path': 'chart/stacked-column100', 'component':'StackedColumn100', 'name': '100% Stacked Column', 'order': '03', 'category': 'Bar Charts' },
    { 'path': 'chart/stacked-bar', 'component':'StackedBar', 'name': 'Stacked Bar', 'order': '03', 'category': 'Bar Charts' },
    { 'path': 'chart/stacked-bar100', 'component':'StackedBar100', 'name': '100% Stacked Bar', 'order': '03', 'category': 'Bar Charts' },   
    { 'path': 'chart/tornado', 'component':'NegativeStack', 'name': 'Negative Stack', 'order': '03', 'category': 'Bar Charts' },
    { 'path': 'chart/range-column', 'component':'RangeColumn', 'name': 'Range Column', 'order': '04', 'category': 'Financial Charts' },
    { 'path': 'chart/range-bar', 'component':'RangeBar', 'name': 'Inversed Range Column', 'order': '04', 'category': 'Financial Charts' },
    { 'path': 'chart/rangearea', 'component':'RangeArea', 'name': 'Range Area', 'order': '04', 'category': 'Financial Charts' },
    { 'path': 'chart/hilo', 'component':'Hilo', 'name': 'Hilo', 'order': '04', 'category': 'Financial Charts' },
    { 'path': 'chart/hiloopenclose', 'component':'HiloOpenClose', 'name': 'Hilo Open Close', 'order': '04', 'category': 'Financial Charts' },
    { 'path': 'chart/candle', 'component':'Candle', 'name': 'Candle', 'order': '04', 'category': 'Financial Charts' },
    { 'path': 'chart/scatter', 'component':'Scatter', 'name': 'Scatter', 'order': '05', 'category': 'Scatter and Bubble' },
    { 'path': 'chart/bubble', 'component':'Bubble', 'name': 'Bubble', 'order': '05', 'category': 'Scatter and Bubble' },
    { 'path': 'chart/waterfall', 'component':'Waterfall', 'name': 'Waterfall', 'order': '06', 'category': 'Other Types' },
    { 'path': 'chart/box-whisker', 'component':'BoxWhisker', 'name': 'Box and Whisker', 'order': '06', 'category': 'Other Types' },
    { 'path': 'chart/error-bar', 'component':'ErrorBarChart', 'name': 'Error Bar', 'order': '06', 'category': 'Other Types' },
    { 'path': 'chart/trend-lines', 'component':'Trend', 'name': 'Trendlines', 'order': '06', 'category': 'Other Types' },
    { 'path': 'chart/combination-series', 'component':'CombinationSeries', 'name': 'Combination Series', 'order': '06', 'category': 'Other Types' },
    { 'path': 'chart/pareto', 'component':'ParetoChart', 'name': 'Pareto Chart', 'order': '06', 'category': 'Other Types' },
    { 'path': 'chart/adindicator', 'component':'AccumulationDistribution', 'name': 'Accumulation Distribution', 'order': '07', 'category': 'Technical Indicators' },
    { 'path': 'chart/atrindicator', 'component':'ATR', 'name': 'ATR', 'order': '07', 'category': 'Technical Indicators' },
    { 'path': 'chart/bollinger', 'component':'Bollinger', 'name': 'Bollinger', 'order': '07', 'category': 'Technical Indicators' },
    { 'path': 'chart/ema', 'component':'EMA', 'name': 'EMA', 'order': '07', 'category': 'Technical Indicators' },
    { 'path': 'chart/macd', 'component':'Macd', 'name': 'MACD', 'order': '07', 'category': 'Technical Indicators' },
    { 'path': 'chart/momentum', 'component':'Momentum', 'name': 'Momentum', 'order': '07', 'category': 'Technical Indicators' },
    { 'path': 'chart/rsi', 'component':'RSI', 'name': 'RSI', 'order': '07', 'category': 'Technical Indicators' },
    { 'path': 'chart/sma', 'component':'SMA', 'name': 'SMA', 'order': '07', 'category': 'Technical Indicators' },
    { 'path': 'chart/stochastic', 'component':'Stochastic', 'name': 'Stochastic', 'order': '07', 'category': 'Technical Indicators' },
    { 'path': 'chart/tma', 'component':'TMA', 'name': 'TMA', 'order': '07', 'category': 'Technical Indicators' },
    { 'path': 'chart/performance', 'component':'Performance', 'name': 'Benchmark', 'order': '08', 'category': 'Performance' },
    { 'path': 'chart/default-pie', 'component': 'Pie', 'name': 'Pie', 'order': '09', 'category': 'Accumulation Charts'},
    { 'path': 'chart/doughnut', 'component': 'AccumulationDoughnut', 'name': 'Doughnut', 'order': '09', 'category': 'Accumulation Charts'},
    { 'path': 'chart/pyramid', 'component': 'Pyramid', 'name': 'Pyramid', 'order': '09', 'category': 'Accumulation Charts'},
    { 'path': 'chart/funnel', 'component': 'Funnel', 'name': 'Funnel', 'order': '09', 'category': 'Accumulation Charts'},
    { 'path': 'chart/default-doughnut', 'component': 'Doughnut', 'name': 'Pie With Legend', 'order': '09', 'category': 'Accumulation Charts'},
    { 'path': 'chart/semi-pie', 'component': 'SemiPie', 'name': 'Semi Pie', 'order': '09', 'category': 'Accumulation Charts'},
    { 'path': 'chart/smartlabels', 'component': 'SmartLabels', 'name': 'Smart Labels', 'order': '09', 'category': 'Accumulation Charts'},
    { 'path': 'chart/drilldown', 'component': 'Drilldown', 'name': 'Drilldown', 'order': '09', 'category': 'Accumulation Charts'},
    { 'path': 'chart/grouping', 'component': 'Grouping', 'name': 'Grouping', 'order': '09', 'category': 'Accumulation Charts'},
    { 'path': 'chart/pie-empty-point', 'component': 'PieEmptyPoint', 'name': 'Empty Points', 'order': '09', 'category': 'Accumulation Charts'},
    { 'path': 'chart/polar-line', 'component':'PolarLine', 'name': 'Line', 'order': '10', 'category': 'Polar Radar'  },
    { 'path': 'chart/polar-spline', 'component':'PolarSpline', 'name': 'Spline', 'order': '10', 'category': 'Polar Radar' },
    { 'path': 'chart/polar-area', 'component':'PolarArea', 'name': 'Area', 'order': '10', 'category': 'Polar Radar' },
    { 'path': 'chart/polar-stackedarea', 'component':'PolarStackedArea', 'name': 'Stacked Area', 'order': '10', 'category': 'Polar Radar' },
    { 'path': 'chart/polar-scatter', 'component':'PolarScatter', 'name': 'Scatter', 'order': '10', 'category': 'Polar Radar'  },
    { 'path': 'chart/polar-column', 'component':'PolarColumn', 'name': 'Column', 'order': '10', 'category': 'Polar Radar' },
    { 'path': 'chart/polar-stackedcolumn', 'component':'PolarStackedColumn', 'name': 'Wind Rose', 'order': '10', 'category': 'Polar Radar' },
    { 'path': 'chart/polar-rangecolumn', 'component':'PolarRangeColumn', 'name': 'Range Column', 'order': '10', 'category': 'Polar Radar'  },
    { 'path': 'chart/local-data', 'component':'LocalData', 'name': 'Local Data', 'order': '11', 'category': 'Data Binding' },
    { 'path': 'chart/remote-data', 'component':'RemoteData', 'name': 'Remote Data', 'order': '11', 'category': 'Data Binding' },
    { 'path': 'chart/numeric-axis', 'component':'Numeric', 'name': 'Numeric Axis', 'order': '12', 'category': 'Chart Axes' },
    { 'path': 'chart/datetime', 'component':'DateTimeAxis', 'name': 'DateTime Axis', 'order': '12', 'category': 'Chart Axes' },
    { 'path': 'chart/category', 'component':'CategoryAxis', 'name': 'Category Axis', 'order': '12', 'category': 'Chart Axes' },
    { 'path': 'chart/indexed-axis', 'component':'IndexedAxis', 'name': 'Indexed Category Axis', 'order': '12', 'category': 'Chart Axes' },
    { 'path': 'chart/log', 'component':'LogAxis', 'name': 'Log Axis', 'order': '12', 'category': 'Chart Axes' },
    { 'path': 'chart/multiple-axis', 'component':'MultipleAxis', 'name': 'Multiple Axis', 'order': '12', 'category': 'Chart Axes' },
    { 'path': 'chart/inversed', 'component':'InversedAxis', 'name': 'Inversed Axis', 'order': '12','category': 'Chart Axes'},    
    { 'path': 'chart/stripline', 'component':'Stripline', 'name': 'Strip Line', 'order': '12','category': 'Chart Axes'},
    { 'path': 'chart/smart-axis-labels', 'component':'SmartAxisLabels', 'name': 'Smart Labels', 'order': '12','category': 'Chart Axes'},
    { 'path': 'chart/symbols', 'component':'Symbols', 'name': 'Symbols', 'order': '13', 'category': 'Chart Customization' },  
    { 'path':'chart/annotation', 'component':'Annotation', 'name':'Annotation', 'order': '13', 'category':'Chart Customization'},
    { 'path': 'chart/datalabel-template', 'component': 'DataLabelTemplate', 'name': 'DataLabel Template', 'order': '13', 'category':'Chart Customization'},
    { 'path': 'chart/vertical', 'component':'VerticalChart', 'name': 'Vertical Chart', 'order': '13','category': 'Chart Customization'}, 
    { 'path': 'chart/empty-point', 'component':'EmptyPoint', 'name': 'Empty Points', 'order': '13', 'category': 'Chart Customization'},    
    { 'path': 'chart/print', 'component':'Print', 'name': 'Print', 'order': '14', 'category': 'Print and Export'},
    { 'path': 'chart/export', 'component':'Export', 'name': 'Export', 'order': '14', 'category': 'Print and Export'},
    { 'path': 'chart/selection', 'component':'SelectionChart', 'name': 'Selection', 'order': '15', 'category': 'User Interaction' },
    { 'path': 'chart/range-selection', 'component':'RangeSelection', 'name': 'Range Selection', 'order': '15', 'category': 'User Interaction' },
    { 'path': 'chart/crosshair', 'component':'CrosshairChart', 'name': 'Crosshair', 'order': '15', 'category': 'User Interaction' },
    { 'path': 'chart/trackball', 'component':'TrackballChart', 'name': 'Trackball', 'order': '15', 'category': 'User Interaction' },
    { 'path': 'chart/zoom', 'component':'Zooming', 'name': 'Zooming and Panning', 'order': '15', 'category': 'User Interaction' }
]