export const LinearGaugeSampleOrder: Object = [
    { 'path': 'linear-gauge/default', 'component': 'Default', 'name': 'Default Functionalities', 'description':'This demo for Essential JS2 Linear Gauge control illustrates the default rendering of linear gauge that measures the values of scales.', 'order': '01', 'category': 'Linear Gauge' },
    { 'path': 'linear-gauge/container', 'component': 'Container', 'name': 'Container', 'description':'This demo for Essential JS2 Linear Gauge control demonstrates the various types of containers available in linear gauge.', 'order': '01', 'category': 'Linear Gauge' },
    { 'path': 'linear-gauge/data', 'component': 'Data', 'name': 'Data Sample', 'description':'This demo for Essential JS2 Linear Gauge control illustrates exercise tracking of an athlete by using ranges, pointers, and annotation features.', 'order': '01', 'category': 'Linear Gauge' },
    { 'path': 'linear-gauge/ranges', 'component': 'Ranges', 'name': 'Ranges', 'description':'This demo for Essential JS2 Linear Gauge control illustrates how to highlight specific regions in an axis by using ranges.', 'order': '01', 'category': 'Linear Gauge' },
    { 'path': 'linear-gauge/axes', 'component': 'Axes', 'name': 'Axes and Pointers', 'description':'This demo for Essential JS2 Linear Gauge control shows various properties available to customize the axes and pointers.', 'order': '01', 'category': 'Linear Gauge' },
    { 'path': 'linear-gauge/annotation', 'component': 'Annotation', 'name': 'Annotation', 'description':'This demo for Essential JS2 Linear Gauge control illustrates the CPU Utilization of a resource by using annotation feature.', 'order': '01', 'category': 'Linear Gauge' },
    { 'path': 'linear-gauge/tooltip', 'component': 'Tooltip', 'name': 'Tooltip', 'description':'This demo for Essential JS2 Linear Gauge control visualizes the tooltip functionality for bar pointer.', 'order': '01', 'category': 'Linear Gauge' },
    { 'path': 'linear-gauge/style', 'component': 'Style', 'name': 'Styles', 'description':'This demo for Essential JS2 Linear Gauge control visualizes the available options for customization.', 'order': '01', 'category': 'Linear Gauge' }
]