export const PivotViewSampleOrder: Object = [
    { 'path': 'pivot-view/default', 'component': 'Default', 'description': 'This demo for Essential JS2 Pivot Table control shows the basic rendering of the pivotgrid with minimum configuration', 'name': 'Default Functionalities', 'order': '01', 'category': 'Pivot Table', 'api': '{"PivotViewComponent":["DataSource"] }' },
    {
        'path': 'pivot-view/local', 'component': 'Local', 'description': 'This demo for Essential JS2 Pivot Table control demonstrate the basic rendering of the pivotgrid widget with local JSON data', 'name': 'Local Data', 'order': '02', 'category': 'Data Binding', 'api': '{"PivotViewComponent":["DataSource"]}',
        'sourceFiles': [
            { 'displayName': 'local.tsx', 'path': 'src/pivot-view/local.tsx' },
            { 'displayName': 'local.jsx', 'path': 'src/pivot-view/local.jsx' },
            { 'displayName': 'localData.json', 'path': 'src/pivot-view/pivot-data/rData.json' }
        ]
    },
    { 'path': 'pivot-view/remote', 'component': 'Remote', 'description': 'This demo for Essential JS2 Pivot Table control demonstrate the basic rendering of the pivotgrid widget with remote data or service data', 'name': 'Remote Data', 'order': '02', 'category': 'Data Binding', 'api': '{"PivotViewComponent":["DataSource"]}' },
    { 'path': 'pivot-view/field-list', 'component': 'FieldList', 'description': 'This demo for Essential JS2 Pivot Table control demonstrate the field list feature of the pivotgrid widget', 'name': 'Field List', 'order': '03', 'category': 'User Interaction', 'api': '{"PivotViewComponent":["DataSource"] }' },
    { 'path': 'pivot-view/grouping-bar', 'component': 'GroupingBarSample', 'description': 'This demo for Essential JS2 Pivot Table control demonstrate the grouping bar feature of the pivotgrid widget', 'name': 'Grouping Bar', 'order': '03', 'category': 'User Interaction', 'api': '{"PivotViewComponent":["DataSource"] }' },
    { 'path': 'pivot-view/conditional-formatting', 'component': 'ConditionalFormattingClass', 'description': 'This demo for Essential JS2 Pivot Table control demonstrate formatting the appearance of the pivot grid cells with values based on the applied conditions', 'name': 'Conditional Formatting', 'order': '03', 'category': 'User Interaction', 'api': '{"PivotViewComponent":["DataSource"] }' },
    { 'path': 'pivot-view/selection', 'component': 'Selection', 'description': 'This demo for Essential JS2 Pivot Table control demonstrate the cell selection feature of the pivotgrid widget', 'name': 'Selection', 'order': '03', 'category': 'User Interaction', 'api': '{"PivotViewComponent":["DataSource"] }', 'type': 'new' },
    { 'path': 'pivot-view/summary-customization', 'component': 'SummaryCustomization', 'description': 'This demo for Essential JS2 Pivot Table control demonstrate the summary customization feature of the pivotgrid widget', 'name': 'Show/Hide Totals', 'order': '03', 'category': 'User Interaction', 'api': '{"PivotViewComponent":["DataSource"] }' },
    { 'path': 'pivot-view/grouping', 'component': 'Grouping', 'description': 'This demo for Essential JS2 Pivot Table control demonstrate the grouping feature for date and number fields', 'name': 'Grouping', 'order': '03', 'category': 'User Interaction', 'api': '{"PivotViewComponent":["DataSource"] }', 'type': 'new' },
    { 'path': 'pivot-view/tool-bar', 'component': 'PivotToolbar', 'description': 'This demo for Essential JS2 Pivot Table control demonstrate the toolbar feature of the pivotgrid widget', 'name': 'Toolbar', 'order': '03', 'category': 'User Interaction', 'api': '{"PivotViewComponent":["DataSource"] }', 'type': 'new' },
    { 'path': 'pivot-view/calculated-field', 'component': 'CalculatedFieldClass', 'description': 'This demo for Essential JS2 Pivot Table control shows calculated field, and it allows users to add calculated items', 'name': 'Calculated Field', 'order': '04', 'category': 'Formula', 'api': '{"PivotViewComponent":["DataSource"] }' },
    { 'path': 'pivot-view/aggregation', 'component': 'Aggregation', 'description': 'This demo for Essential JS2 Pivot Table control shows different types of aggregation for value fields', 'name': 'Aggregation', 'order': '04', 'category': 'Formula', 'api': '{"PivotViewComponent":["DataSource"] }' },
    { 'path': 'pivot-view/sorting', 'component': 'Sorting', 'description': 'This demo for Essential JS2 Pivot Table control shows ordering(sorting) of fields either in ascending or descending order', 'name': 'Default Sorting', 'order': '05', 'category': 'Sorting', 'api': '{"PivotViewComponent":["DataSource"]}' },
    { 'path': 'pivot-view/value-sorting', 'component': 'ValueSorting', 'description': 'This demo for Essential JS2 Pivot Table control shows sorting values on column or row wise in ascending or descending order', 'name': 'Value Sorting', 'order': '05', 'category': 'Sorting', 'api': '{"PivotViewComponent":["DataSource"] }' },
    { 'path': 'pivot-view/filtering', 'component': 'Filtering', 'description': 'This demo for Essential JS2 Pivot Table control demonstrate member filtering of field headers either by including or excluding them', 'name': 'Default Filtering', 'order': '06', 'category': 'Filtering', 'api': '{"PivotViewComponent":["DataSource"]}' },
    { 'path': 'pivot-view/label-filtering', 'component': 'LabelFilter', 'description': 'This demo for Essential JS2 Pivot Table control demonstrate label filtering of field headers either by including or excluding them', 'name': 'Label Filtering', 'order': '06', 'category': 'Filtering', 'api': '{"PivotViewComponent":["DataSource"]}' },
    { 'path': 'pivot-view/value-filtering', 'component': 'ValueFilter', 'description': 'This demo for Essential JS2 Pivot Table control demonstrate the filtering of field headers based on the grand total (value based)', 'name': 'Value Filtering', 'order': '06', 'category': 'Filtering', 'api': '{"PivotViewComponent":["DataSource"]}' },
    { 'path': 'pivot-view/chart', 'component': 'ChartIntegration', 'description': 'This demo for Essential JS2 Pivot Table control demonstrate integration of pivot table data into a simple chart widget', 'name': 'Chart', 'order': '07', 'category': 'Integration', 'api': '{"PivotViewComponent":["DataSource"]}', 'type': 'update' },
    { 'path': 'pivot-view/external-binding', 'component': 'Integration', 'description': 'This demo for Essential JS2 Pivot Table control demonstrate the rendering of chart widget with cell selection option', 'name': 'External Binding', 'order': '07', 'category': 'Integration', 'api': '{"PivotViewComponent":["DataSource"]}', 'type': 'new' },
    { 'path': 'pivot-view/virtual-scrolling', 'component': 'VirtualScrolling', 'description': 'This demo for Essential JS2 Pivot Table control shows virtual scrolling option available vertically and horizontally to load large records with ease', 'name': 'Virtual Scrolling', 'order': '08', 'category': 'Scrolling', 'api': '{"PivotViewComponent":["DataSource"] }' },
    { 'path': 'pivot-view/cell-template', 'component': 'CellTemplate', 'description': 'This demo for Essential JS2 Pivot Table control demonstrate cell template option on cells of the pivotgrid widget', 'name': 'Cell Template', 'order': '09', 'category': 'Customization', 'api': '{"PivotViewComponent":["DataSource"] }', 'type': 'new' },
    { 'path': 'pivot-view/drill-through', 'component': 'DrillThroughComponent', 'description': 'This demo for Essential JS2 Pivot Table control shows the raw items of any value cells in pivot grid', 'name': 'Drill Through', 'order': '10', 'category': 'Miscellaneous', 'api': '{"PivotViewComponent":["DataSource"] }' },
    { 'path': 'pivot-view/editing', 'component': 'Editing', 'description': 'This demo for Essential JS2 Pivot Table control allows to edit, add and delete the value cells in pivot grid', 'name': 'Editing', 'order': '10', 'category': 'Miscellaneous', 'api': '{"PivotViewComponent":["DataSource"] }' },
    { 'path': 'pivot-view/hyper-link', 'component': 'HyperLink', 'description': 'This demo for Essential JS2 Pivot Table control shows hyperlink option on cells of the pivotgrid widget', 'name': 'Hyperlink', 'order': '10', 'category': 'Miscellaneous', 'api': '{"PivotViewComponent":["DataSource"] }' },
    { 'path': 'pivot-view/defer-update', 'component': 'DeferUpdate', 'description': 'This demo for Essential JS2 Pivot Table control demonstrate defer layout update feature of the pivotgrid widget', 'name': 'Defer Layout Update', 'order': '10', 'category': 'Miscellaneous', 'api': '{"PivotViewComponent":["DataSource"] }' },
    { 'path': 'pivot-view/exporting', 'component': 'Exporting', 'description': 'This demo for Essential JS2 Pivot Table control demonstrate client-side exporting of the pivotgrid widget to Excel, CSV and PDF formats', 'name': 'Export', 'order': '10', 'category': 'Miscellaneous', 'api': '{"PivotViewComponent":["DataSource"] }' }
];