export const GridSampleOrder: Object = [
    { 'path': 'grid/default', 'component': 'Default', 'name': 'Default Functionalities', 'order': '01', 'category': 'GRID' },
    { 'path': 'grid/gridlines', 'component': 'GridLines', 'name': 'GridLines', 'order': '01', 'category': 'GRID' },
    { 'path': 'grid/paging', 'component': 'Paging', 'name': 'Paging', 'order': '01', 'category': 'GRID' },
    { 'path': 'grid/filtering', 'component': 'Filtering', 'name': 'Filtering', 'order': '01', 'category': 'GRID' },
    { 'path': 'grid/filtermenu', 'component': 'FilterMenu', 'name': 'Filtering Menu', 'order': '01', 'category': 'GRID' },
    { 'path': 'grid/grouping', 'component': 'Grouping', 'name': 'Grouping', 'order': '01', 'category': 'GRID' },
    { 'path': 'grid/sorting', 'component': 'Sorting', 'name': 'Sorting', 'order': '01', 'category': 'GRID' },
    { 'path': 'grid/scrolling', 'component': 'Scrolling', 'name': 'Default Scrolling', 'order': '05', 'category': 'SCROLLING' },
    { 'path': 'grid/virtualization', 'component': 'Virtualization', 'name': 'Virtual Scrolling', 'order': '05', 'category': 'SCROLLING' },
    { 'path': 'grid/searching', 'component': 'Searching', 'name': 'Searching', 'order': '01', 'category': 'GRID' },
    { 'path': 'grid/masterdetail', 'component': 'MasterDetail', 'name': 'Master/Detail', 'order': '01', 'category': 'GRID' },
    { 'path': 'grid/rowdraganddrop', 'component': 'Source', 'name': 'Row Drag and Drop', 'order': '01', 'category': 'GRID', 'hideOnDevice': 'true' },
    { 'path': 'grid/hierarchy', 'component': 'Hierarchy', 'name': 'Hierarchy Grid', 'order': '01', 'category': 'GRID' },
    { 'path': 'grid/clipboard', 'component': 'Clipboard', 'name': 'Clipboard', 'order': '01', 'category': 'GRID' },
    { 'path': 'grid/localbinding', 'component': 'Localbinding', 'name': 'Local Binding', 'order': '02', 'category': 'DATABINDING' },
    { 'path': 'grid/remotedata', 'component': 'RemoteDataBinding', 'name': 'Remote Binding', 'order': '02', 'category': 'DATABINDING' },
    { 'path': 'grid/showhide', 'component': 'ShowHide', 'name': 'Show Hide Column', 'order': '03', 'category': 'COLUMN' },
    { 'path': 'grid/stackedheader', 'component': 'StackedHeader', 'name': 'Stacked Header', 'order': '03', 'category': 'COLUMN' },
    { 'path': 'grid/autowrap', 'component': 'AutoWrap', 'name': 'AutoWrap Column cells', 'order': '03', 'category': 'COLUMN' },
    { 'path': 'grid/reorder', 'component': 'Reordering', 'name': 'Reorder Columns', 'order': '03', 'category': 'COLUMN' },
    { 'path': 'grid/selection', 'component': 'Selectioning', 'name': 'Default Selection', 'order': '04', 'category': 'SELECTION' },
    { 'path': 'grid/selectionapi', 'component': 'SelectionAPI', 'name': 'Selection API', 'order': '04', 'category': 'SELECTION' },
    { 'path': 'grid/checkboxselection', 'component': 'CheckboxSelection', 'name': 'Checkbox Selection', 'order': '04', 'category': 'SELECTION' },
    { 'path': 'grid/columnchooser', 'component': 'ColumnChooser', 'name': 'Column Chooser', 'order': '03', 'category': 'COLUMN' },
    { 'path': 'grid/columnresizing', 'component': 'ColumnResizing', 'name': 'Column Resizing', 'order': '03', 'category': 'COLUMN' },
    { 'path': 'grid/normaledit', 'component': 'NormalEdit', 'name': 'Inline Editing', 'order': '06', 'category': 'EDITING' },
    { 'path': 'grid/dialogedit', 'component': 'DialogEdit', 'name': 'Dialog Editing', 'order': '06', 'category': 'EDITING' },
    { 'path': 'grid/batch', 'component': 'BatchEdit', 'name': 'Batch Editing', 'order': '06', 'category': 'EDITING' },
    { 'path': 'grid/command-column', 'component': 'CommandColumnEdit', 'name': 'CommandColumn', 'order': '06', 'category': 'EDITING'},
    { 'path': 'grid/exporting', 'component': 'Exporting', 'name': 'Basic', 'order': '07', 'category': 'EXPORTING' },
    { 'path': 'grid/multipleexporting', 'component': 'MultipleExporting', 'name': 'MultipleExporting', 'order': '07', 'category': 'EXPORTING' },
    { 'path': 'grid/rowheight', 'component': 'RowHeight', 'name': 'Row Height', 'order': '01', 'category': 'GRID' },
    { 'path': 'grid/columnmenu', 'component': 'ColumnMenuSample', 'name': 'Column Menu', 'order': '03', 'category': 'COLUMN', 'type': 'new' },
    { 'path': 'grid/contextmenu', 'component': 'ContextMenuSample', 'name': 'Context Menu', 'order': '01', 'category': 'GRID', 'type': 'new' },
    { 'path': 'grid/columnspanning', 'component': 'ColumnSpanning', 'name': 'Column Spanning', 'order': '03', 'category': 'COLUMN', 'type': 'new' }
]