export const MultiSelectSampleOrder:Object = [
    { 'path': 'multiselect/default', 'component':'Default', 'name': 'Default Functionalities', 'order': '01', 'category': 'MultiSelect', 'api': '{"MultiSelect": ["mode", "placeholder"]}' },
    { 'path': 'multiselect/data-binding', 'component':'Data', 'name': 'Data Binding', 'order': '01', 'category': 'MultiSelect', 'api': '{"MultiSelect": ["query", "dataSource", "fields", "sortOrder", "placeholder"]}' },
    { 'path': 'multiselect/grouping', 'component':'Grouping', 'name': 'Grouping', 'order': '01', 'category': 'MultiSelect', 'api': '{"MultiSelect": ["dataSource", "fields", "placeholder"]}' },
    { 'path': 'multiselect/template', 'component':'Templates', 'name': 'Templates', 'order': '01', 'category': 'MultiSelect', 'api': '{"MultiSelect": ["dataSource", "fields", "headerTemplate", "itemTemplate", "valueTemplate", "mode", "placeholder"]}' },
    { 'path': 'multiselect/filtering', 'component':'Filtering', 'name': 'Filtering', 'order': '01', 'category': 'MultiSelect', 'api': '{"MultiSelect": ["query", "dataSource", "fields", "placeholder", "allowFiltering", "filtering"]}' },
    { 'path': 'multiselect/customtag', 'component':'CustomTag', 'name': 'Custom Values', 'order': '01', 'category': 'MultiSelect', 'api': '{"MultiSelect": ["dataSource", "fields", "placeholder", "mode", "allowCustomValue"]}' },
    { 'path': 'multiselect/chip-customization', 'component':'ChipCustomization', 'name': 'Chip Customization', 'order': '01', 'category': 'MultiSelect', 'api': '{"MultiSelect": ["dataSource", "fields", "placeholder", "mode", "tagging"]}', 'type': 'new' },
    { 'path': 'multiselect/checkbox', 'component':'CheckBox', 'name': 'CheckBox', 'order': '01', 'category': 'MultiSelect', 'api': '{"MultiSelect": ["dataSource", "fields", "placeholder"]}', 'type': 'new' },
    { 'path': 'multiselect/selectionlimit', 'component':'SelectionLimit', 'name': 'Selection Limit', 'order': '01', 'category': 'MultiSelect', 'api': '{"MultiSelect": ["dataSource", "fields", "placeholder", "maximumSelectionLength"]}', 'type': 'new' },
    { 'path': 'multiselect/diacritics-filtering', 'component':'DiacriticsFiltering', 'name': 'Diacritics Filtering', 'order': '01', 'category': 'MultiSelect', 'api': '{"MultiSelect": ["dataSource", "ignoreAccent", "placeholder"]}', 'type': 'new' }
]