"use strict";
var __extends = (this && this.__extends) || (function () {
    var extendStatics = Object.setPrototypeOf ||
        ({ __proto__: [] } instanceof Array && function (d, b) { d.__proto__ = b; }) ||
        function (d, b) { for (var p in b) if (b.hasOwnProperty(p)) d[p] = b[p]; };
    return function (d, b) {
        extendStatics(d, b);
        function __() { this.constructor = d; }
        d.prototype = b === null ? Object.create(b) : (__.prototype = b.prototype, new __());
    };
})();
Object.defineProperty(exports, "__esModule", { value: true });
var React = require("react");
var ej2_react_inputs_1 = require("@syncfusion/ej2-react-inputs");
var sample_base_1 = require("../common/sample-base");
require("./sample.css");
var Default = /** @class */ (function (_super) {
    __extends(Default, _super);
    function Default() {
        return _super !== null && _super.apply(this, arguments) || this;
    }
    Default.prototype.floatFocus = function (args) {
        args.target.parentElement.classList.add('e-input-focus');
    };
    Default.prototype.floatBlur = function (args) {
        args.target.parentElement.classList.remove('e-input-focus');
    };
    Default.prototype.onIconClick = function (args) {
        args.persist();
        setTimeout(function () {
            args.target.classList.add('e-input-btn-ripple');
        }, 500);
    };
    Default.prototype.onIconUnClick = function (args) {
        args.target.classList.remove('e-input-btn-ripple');
    };
    Default.prototype.render = function () {
        return (React.createElement("div", { className: 'control-pane' },
            React.createElement("div", { className: 'control-section input-content-wrapper' },
                React.createElement("div", { className: "row custom-margin material2" },
                    React.createElement("div", { className: "col-xs-6 col-sm-6 col-lg-6 col-md-6" },
                        React.createElement("b", null, "Outlined and Filled"))),
                React.createElement("div", { className: "row custom-margin custom-padding-5 material2" },
                    React.createElement("div", { className: "col-xs-6 col-sm-6 col-lg-6 col-md-6" },
                        React.createElement(ej2_react_inputs_1.TextBoxComponent, { placeholder: "Outlined", cssClass: "e-outline", floatLabelType: "Auto" })),
                    React.createElement("div", { className: "col-xs-6 col-sm-6 col-lg-6 col-md-6" },
                        React.createElement(ej2_react_inputs_1.TextBoxComponent, { placeholder: "Filled", cssClass: "e-filled", floatLabelType: "Auto" }))),
                React.createElement("div", { className: "row custom-margin" },
                    React.createElement("div", { className: "col-xs-6 col-sm-6 col-lg-6 col-md-6" },
                        React.createElement("b", null, "Floating Label"))),
                React.createElement("div", { className: "row custom-margin custom-padding-5" },
                    React.createElement("div", { className: "col-xs-6 col-sm-6 col-lg-6 col-md-6" },
                        React.createElement(ej2_react_inputs_1.TextBoxComponent, { placeholder: "First Name", floatLabelType: "Auto" })),
                    React.createElement("div", { className: "col-xs-6 col-sm-6 col-lg-6 col-md-6" },
                        React.createElement(ej2_react_inputs_1.TextBoxComponent, { placeholder: "Last Name", floatLabelType: "Auto", enableRtl: true }))),
                React.createElement("div", { className: "row custom-margin custom-padding-5" },
                    React.createElement("div", { className: "col-xs-12 col-sm-12 col-lg-12 col-md-12" },
                        React.createElement("div", { className: "e-float-input e-input-group" },
                            React.createElement("input", { type: "text", onFocus: this.floatFocus, onBlur: this.floatBlur, required: true }),
                            React.createElement("span", { className: "e-float-line" }),
                            React.createElement("label", { className: "e-float-text" }, "Country"),
                            React.createElement("span", { className: "e-input-group-icon e-spin-down", onMouseDown: this.onIconClick, onMouseUp: this.onIconUnClick })))),
                React.createElement("div", { className: "row custom-margin" },
                    React.createElement("div", { className: "col-xs-6 col-sm-6 col-lg-6 col-md-6" },
                        React.createElement("b", null, "Inputs"))),
                React.createElement("div", { className: "row custom-margin" },
                    React.createElement("div", { className: "col-xs-6 col-sm-6 col-lg-6 col-md-6" },
                        React.createElement("div", { className: "e-input-group" },
                            React.createElement("input", { className: "e-input", type: "text", onFocus: this.floatFocus, onBlur: this.floatBlur, placeholder: "Enter Name" }))),
                    React.createElement("div", { className: "col-xs-6 col-sm-6 col-lg-6 col-md-6" },
                        React.createElement("div", { className: "e-input-group e-rtl" },
                            React.createElement("input", { className: "e-input", onFocus: this.floatFocus, onBlur: this.floatBlur, type: "text", placeholder: "Last Name" })))),
                React.createElement("div", { className: "row custom-margin" },
                    React.createElement("div", { className: "col-xs-6 col-sm-6 col-lg-6 col-md-6" },
                        React.createElement("div", { className: "e-input-group" },
                            React.createElement("input", { className: "e-input", onFocus: this.floatFocus, onBlur: this.floatBlur, type: "password", placeholder: "Password", defaultValue: "password" }))),
                    React.createElement("div", { className: "col-xs-6 col-sm-6 col-lg-6 col-md-6" },
                        React.createElement("div", { className: "e-input-group" },
                            React.createElement("input", { className: "e-input", onFocus: this.floatFocus, onBlur: this.floatBlur, type: "email", placeholder: "Enter Email" })))),
                React.createElement("div", { className: "row custom-margin" },
                    React.createElement("div", { className: "col-xs-6 col-sm-6 col-lg-6 col-md-6" },
                        React.createElement("div", { className: "e-input-group e-disabled" },
                            React.createElement("input", { className: "e-input", onFocus: this.floatFocus, onBlur: this.floatBlur, type: "text", placeholder: "Disabled", disabled: true }))),
                    React.createElement("div", { className: "col-xs-6 col-sm-6 col-lg-6 col-md-6" },
                        React.createElement("div", { className: "e-input-group" },
                            React.createElement("input", { className: "e-input", onFocus: this.floatFocus, onBlur: this.floatBlur, type: "text", placeholder: "Enter Name", value: "Readonly", readOnly: true })))),
                React.createElement("div", { className: "row custom-margin" },
                    React.createElement("div", { className: "col-xs-6 col-sm-6 col-lg-6 col-md-6" },
                        React.createElement("b", null, "Validation States"))),
                React.createElement("div", { className: "row custom-margin" },
                    React.createElement("div", { className: "col-xs-4 col-sm-4 col-lg-4 col-md-4" },
                        React.createElement("div", { className: "e-input-group e-success" },
                            React.createElement("input", { className: "e-input", onFocus: this.floatFocus, onBlur: this.floatBlur, type: "text", placeholder: "Success" }))),
                    React.createElement("div", { className: "col-xs-4 col-sm-4 col-lg-4 col-md-4" },
                        React.createElement("div", { className: "e-input-group e-warning" },
                            React.createElement("input", { className: "e-input", type: "text", onFocus: this.floatFocus, onBlur: this.floatBlur, placeholder: "Warning" }))),
                    React.createElement("div", { className: "col-xs-4 col-sm-4 col-lg-4 col-md-4" },
                        React.createElement("div", { className: "e-input-group e-error" },
                            React.createElement("input", { className: "e-input", onFocus: this.floatFocus, onBlur: this.floatBlur, type: "text", placeholder: "Error" })))),
                React.createElement("div", { className: "row custom-margin" },
                    React.createElement("div", { className: "col-xs-6 col-sm-6 col-lg-6 col-md-6" },
                        React.createElement("b", null, "Sizing"))),
                React.createElement("div", { className: "row custom-margin" },
                    React.createElement("div", { className: "col-xs-6 col-sm-6 col-lg-6 col-md-6" },
                        React.createElement("div", { className: "e-input-group e-small" },
                            React.createElement("input", { className: "e-input", onFocus: this.floatFocus, onBlur: this.floatBlur, type: "text", placeholder: "Small" }))),
                    React.createElement("div", { className: "col-xs-6 col-sm-6 col-lg-6 col-md-6" },
                        React.createElement("div", { className: "e-input-group" },
                            React.createElement("input", { className: "e-input", onFocus: this.floatFocus, onBlur: this.floatBlur, type: "text", placeholder: "Normal" })))),
                React.createElement("div", { className: "row custom-margin" },
                    React.createElement("div", { className: "col-xs-6 col-sm-6 col-lg-6 col-md-6" },
                        React.createElement("b", null, "Input & Elements"))),
                React.createElement("div", { className: "row custom-margin" },
                    React.createElement("div", { className: "col-xs-6 col-sm-6 col-lg-6 col-md-6" },
                        React.createElement("div", { className: "e-input-group" },
                            React.createElement("input", { className: "e-input", onFocus: this.floatFocus, onBlur: this.floatBlur, type: "text", placeholder: "Date of Birth" }),
                            React.createElement("span", { className: "e-input-group-icon e-input-calendar", onMouseDown: this.onIconClick, onMouseUp: this.onIconUnClick }))),
                    React.createElement("div", { className: "col-xs-6 col-sm-6 col-lg-6 col-md-6" },
                        React.createElement("div", { className: "e-input-group e-float-icon-left" },
                            React.createElement("span", { className: "e-input-group-icon e-input-picture", onMouseDown: this.onIconClick, onMouseUp: this.onIconUnClick }),
                            React.createElement("div", { className: "e-input-in-wrap" },
                                React.createElement("input", { className: "e-input", onFocus: this.floatFocus, onBlur: this.floatBlur, type: "text", placeholder: "Upload Picture" })))))),
            React.createElement("div", { id: "action-description" },
                React.createElement("p", null,
                    "This example demonstrates the default functionalities of the ",
                    React.createElement("code", null, "TextBox"),
                    " component. Type a character in the TextBox element or focus-in to the TextBox for floating the label text. The label will be positioned back to TextBox on focus-out without value.")),
            React.createElement("div", { id: "description" },
                React.createElement("p", null, "A TextBoxes are an input element that allows to get input from the user. It allows the user either to edit or display the input values."),
                React.createElement("br", null),
                React.createElement("table", { className: "custom-width" },
                    React.createElement("tbody", null,
                        React.createElement("tr", null,
                            React.createElement("th", null, "Types"),
                            React.createElement("th", null, "Description")),
                        React.createElement("tr", null,
                            React.createElement("td", null, "Outlined & Filled textbox"),
                            React.createElement("td", null,
                                "You can render the following two types of text fields in the material theme by adding ",
                                React.createElement("b", null, "e-outline"),
                                " and ",
                                React.createElement("b", null, "e-filled"),
                                " class to cssClass API.",
                                React.createElement("ul", null,
                                    React.createElement("li", null, "Filled text fields"),
                                    React.createElement("li", null, "Outlined text fields")),
                                " ")),
                        React.createElement("tr", null,
                            React.createElement("td", null, "Floating Label"),
                            React.createElement("td", null,
                                "You can render floating textbox with ",
                                React.createElement("b", null, "e-float-input"),
                                " class added and need to maintain the following structure of elements.",
                                React.createElement("ul", null,
                                    React.createElement("li", null,
                                        "Create group element with ",
                                        React.createElement("b", null, "e-float-input"),
                                        " class added."),
                                    React.createElement("li", null,
                                        "Input element with ",
                                        React.createElement("b", null, "required"),
                                        " attribute."),
                                    React.createElement("li", null,
                                        "Span element with ",
                                        React.createElement("b", null, "e-float-line"),
                                        " class."),
                                    React.createElement("li", null,
                                        "Label element with ",
                                        React.createElement("b", null, "e-float-text"),
                                        " class.")),
                                " ")),
                        React.createElement("tr", null,
                            React.createElement("td", null, "Floating Label & Elements"),
                            React.createElement("td", null,
                                "You can render floating textbox with icons added with in group element ",
                                React.createElement("b", null, "e-input-group"),
                                " and need to maintain the following structure of elements.",
                                React.createElement("ul", null,
                                    React.createElement("li", null,
                                        "Create group element with ",
                                        React.createElement("b", null, "e-float-input"),
                                        " class added."),
                                    React.createElement("li", null,
                                        "Input element with ",
                                        React.createElement("b", null, "required"),
                                        " attribute."),
                                    React.createElement("li", null,
                                        "Span element with ",
                                        React.createElement("b", null, "e-float-line"),
                                        " class."),
                                    React.createElement("li", null,
                                        "Label element with ",
                                        React.createElement("b", null, "e-float-text"),
                                        " class."),
                                    React.createElement("li", null,
                                        "Append or prepend the span element with class ",
                                        React.createElement("b", null, "e-input-group-icon"),
                                        " added.")))),
                        React.createElement("tr", null,
                            React.createElement("td", null, "Default TextBox"),
                            React.createElement("td", null,
                                React.createElement("div", { className: "custom-padding-bottom-10" },
                                    " You can render textbox by adding class as ",
                                    React.createElement("b", null, "e-input"),
                                    ".You can also render textbox as group by adding parent element with ",
                                    React.createElement("b", null, "e-input-group"),
                                    " class added."))),
                        React.createElement("tr", null,
                            React.createElement("td", null, "RTL TextBox"),
                            React.createElement("td", null,
                                React.createElement("div", { className: "custom-padding-bottom-10" },
                                    "Set ",
                                    React.createElement("b", null, "e-input"),
                                    " and ",
                                    React.createElement("b", null, "e-rtl"),
                                    " classes to render textbox in right to left direction. For rendering group in RTL mode , class list will be like ",
                                    React.createElement("b", null, "e-input-group e-rtl"),
                                    "."))),
                        React.createElement("tr", null,
                            React.createElement("td", null, "Disabled TextBox"),
                            React.createElement("td", null,
                                React.createElement("div", { className: "custom-padding-bottom-10" },
                                    "You set html disabled attribute to textbox. For parent group element , you can disable it by adding ",
                                    React.createElement("b", null, "e-disabled"),
                                    "                    class."))),
                        React.createElement("tr", null,
                            React.createElement("td", null, "Readonly TextBox"),
                            React.createElement("td", null,
                                React.createElement("div", { className: "custom-padding-bottom-10" }, "You set html readonly attribute to textbox."))),
                        React.createElement("tr", null,
                            React.createElement("td", null, "Validation states"),
                            React.createElement("td", null,
                                React.createElement("div", { className: "custom-padding-bottom-10" },
                                    "You can apply validation states success, warning, error to the textbox with the corresponding classes added to the input element such as ",
                                    React.createElement("b", null, "e-success"),
                                    ", ",
                                    React.createElement("b", null, "e-warning"),
                                    ", ",
                                    React.createElement("b", null, "e-error"),
                                    "."))),
                        React.createElement("tr", null,
                            React.createElement("td", null, "Sizing"),
                            React.createElement("td", null,
                                React.createElement("div", { className: "custom-padding-bottom-10" },
                                    "You can render small sizing textbox by adding ",
                                    React.createElement("b", null, "e-small"),
                                    " class to the input element. By default normal size considered."))),
                        React.createElement("tr", null,
                            React.createElement("td", null, "Input & elements"),
                            React.createElement("td", null,
                                "You can render textbox with icons in the below format,",
                                React.createElement("ul", null,
                                    React.createElement("li", null,
                                        "Create group element with ",
                                        React.createElement("b", null, "e-input-group"),
                                        " class added."),
                                    React.createElement("li", null,
                                        "Add input element with ",
                                        React.createElement("b", null, "e-input"),
                                        " and span element with ",
                                        React.createElement("b", null, "e-input-group-icon"),
                                        " inside the input group element."),
                                    React.createElement("li", null,
                                        "You can add the icon either before or after the textbox by placing ",
                                        React.createElement("b", null, "e-input-group-icon"),
                                        " class named element in specific place.")))))),
                React.createElement("br", null))));
    };
    return Default;
}(sample_base_1.SampleBase));
exports.Default = Default;
