export const ButtonSampleOrder: Object = [
    { 'path': 'button/default', 'component': 'Default', 'name': 'Default Functionalities', 'order': '01', 'category': 'Button', 'api': '{"ButtonComponent":["isPrimary", "cssClass", "iconCss", "isToggle", "iconPosition", "content"] }', 'description': 'This example demonstrates the types (flat, toogle, outline, round), sizes and styles (primary, success, info, warning) of the Syncfusion React button', 'ftName': 'button' },
    { 'path': 'button/button-group', 'component': 'ButtonGroup', 'name': 'Button Group', 'order': '01', 'category': 'Button', 'description': 'This example demonstrates the behaviors (default, checkbox, radio) of the Syncfusion React ButtonGroup.', 'ftName': 'button-group' },
    { 'path': 'button/checkbox', 'component': 'CheckBox', 'name': 'Checkbox', 'order': '01', 'category': 'Button', 'api': '{"CheckBoxComponent":["label", "checked", "indeterminate", "disabled", "change"] }', 'description': 'This example demonstrates the three different states (checked, unchecked, indeterminate) of the Syncfusion React CheckBox.', 'ftName': 'checkbox' },
    { 'path': 'button/radio-button', 'component': 'RadioButton', 'name': 'Radio Button', 'order': '01', 'category': 'Button', 'api': '{"RadioButtonComponent":["label", "name", "value", "checked"] }', 'description': 'This example demonstrates the group functionality of the Syncfusion React RadioButton with checked and unchecked states.', 'ftName': 'radio-button' },
    { 'path': 'button/dropdown-button', 'component': 'DropDownButton', 'name': 'Dropdown Menu', 'order': '01', 'category': 'Button', 'api': '{"DropDownButtonComponent":["items", "cssClass", "iconCss"] }', 'description': 'This example demonstrates the usecases of the Syncfusion React DropDownButton with icons, text and separator in popup action items.', 'ftName': 'dropdown-menu' },
    { 'path': 'button/split-button', 'component': 'SplitButton', 'name': 'Split Button', 'order': '01', 'category': 'Button', 'api': '{"SplitButtonComponent":["items", "content", "iconCss", "beforeItemRender"] }', 'description': 'This example demonstrates the usecases of the Syncfusion React SplitButton with icons and text in primary splitbutton.', 'ftName': 'split-button' },
    { 'path': 'button/switch', 'component': 'Switch', 'name': 'Switch', 'order': '01', 'category': 'Button', 'api': '{"SwitchComponent":["checked", "disabled"] }', 'description': 'This example demonstrates the toggle states (checked, unchecked) of the Syncfusion React Toggle Switch.', 'ftName': 'toggle-switch-button' },
    { 'path': 'button/progress-button', 'component': 'ProgressButton', 'name': 'Progress Button', 'order': '01', 'category': 'Button', 'api': '{"ProgressButtonComponent":["content", "iconCss", "cssClass", "duration", "disabled", "isPrimary", "enableProgress", "end", "begin", "spinSettings", "animationSettings"] }','description': 'This example demonstrates the different functionalities of the Syncfusion React ProgressButton with spinner and progress indicator.', 'ftName': 'progress-button' }
];
