export const ButtonSampleOrder: Object = [
    { 'path': 'button/default', 'component': 'Default', 'name': 'Default Functionalities', 'order': '01', 'category': 'Button', 'api': '{"ButtonComponent":["isPrimary", "cssClass", "iconCss", "isToggle", "iconPosition", "content"] }', 'description': 'This demo for Essential JS2 Button shows the its types (flat, toggle, outline, round, icon), sizes and styles (primary, success, info, warning) of buttons.', 'ftName': 'button' },
    { 'path': 'button/button-group', 'component': 'ButtonGroup', 'name': 'ButtonGroup', 'order': '01', 'category': 'Button', 'description': 'This demo for Syncfusion Essential JS2 Button Group control shows the horizontal group of buttons. This supports radio and checkbox type behaviors.', 'ftName': 'button-group' },
    { 'path': 'button/check-box', 'component': 'CheckBox', 'name': 'CheckBox', 'order': '01', 'category': 'Button', 'api': '{"CheckBoxComponent":["label", "checked", "indeterminate", "disabled", "change"] }', 'description': 'This demo for Essential JS2 Check Box control shows the checked, unchecked, and indeterminate states of checkbox. It also provide supports for specifying label', 'ftName': 'checkbox' },
    { 'path': 'button/radio-button', 'component': 'RadioButton', 'name': 'RadioButton', 'order': '01', 'category': 'Button', 'api': '{"RadioButtonComponent":["label", "name", "value", "checked"] }', 'description': 'This demo for Syncfusion Essential JS2 RadioButton control shows the radio button group functionality. It contains checked and unchecked state.', 'ftName': 'radio-button' },
    { 'path': 'button/drop-down-button', 'component': 'DropDownButton', 'name': 'DropDownButton', 'order': '01', 'category': 'Button', 'api': '{"DropDownButtonComponent":["items", "cssClass", "iconCss"] }', 'description': 'This demo for Essential JS2 DropDown Button control shows the use cases of drop down button. The popup contains action items with text, icons and separator.', 'ftName': 'dropdown-menu' },
    { 'path': 'button/split-button', 'component': 'SplitButton', 'name': 'SplitButton', 'order': '01', 'category': 'Button', 'api': '{"SplitButtonComponent":["items", "content", "iconCss", "beforeItemRender"] }', 'description': 'This demo for Syncfusion Essential JS2 SplitButton control shows the use cases of split button. The icons, text and both can be loaded in primary splitbutton.', 'ftName': 'split-button' },
    { 'path': 'button/switch', 'component': 'Switch', 'name': 'Switch', 'order': '01', 'category': 'Button', 'api': '{"SwitchComponent":["checked", "disabled"] }', 'description': 'This demo for Syncfusion Essential JS2 Switch control allows to toggle between the checked and unchecked states. It also provides support for custom UI.', 'ftName': 'toggle-switch-button' },
    { 'path': 'button/progress-button', 'component': 'ProgressButton', 'name': 'ProgressButton', 'order': '01', 'category': 'Button', 'api': '{"ProgressButtonComponent":["content", "iconCss", "cssClass", "duration", "disabled", "isPrimary", "enableProgress", "end", "begin", "spinSettings", "animationSettings"] }','description': 'This demo for Essential JS2 Progress button has progress indicator and spinner. It supports texts, icons, styles, sizes, positions, and its customization.', 'ftName': 'progress-button' }
];
