export const CircularGaugeSampleOrder:Object = [
    { 'path': 'circular-gauge/default', 'component':'Default', 'name': 'Default Functionalities', 'description':'This demo for Essential JS2 Circular Gauge control illustrates the default rendering of circular gauge.', 'order': '01', 'category': 'CIRCULAR GAUGE' },
    { 'path': 'circular-gauge/range', 'component':'Range', 'name': 'Range', 'description':'This demo for Essential JS2 Circular Gauge control illustrates how to highlight specific regions in an axis by using ranges.', 'order': '01', 'category': 'CIRCULAR GAUGE' },
    { 'path': 'circular-gauge/labels', 'component':'Labels', 'name': 'Tick and Labels', 'type': 'update', 'description':'This demo for Essential JS2 Circular Gauge control shows various properties available to customize the ticks and labels of an axis.', 'order': '01', 'category': 'CIRCULAR GAUGE' },
    { 'path': 'circular-gauge/annotation', 'component':'AnnotationsSample', 'name': 'Annotations', 'description':'This demo for Essential JS2 Circular Gauge control illustrates a clock by using annotation feature in the gauge.', 'order': '01', 'category': 'CIRCULAR GAUGE' },
    { 'path': 'circular-gauge/customization', 'component':'Customization', 'name': 'Gauge Customization', 'description':'This demo for Essential JS2 Circular Gauge control shows the properties required to customize the pointers.', 'order': '01', 'category': 'CIRCULAR GAUGE' },
    { 'path': 'circular-gauge/semi-circular-gauge', 'component':'SemiGauge', 'name': 'Semi-Circular Gauge', 'order': '01', 'category': 'CIRCULAR GAUGE', 'type': 'new' },
    { 'path': 'circular-gauge/arc-gauge', 'component':'ArcGauge', 'name': 'Arc Gauge', 'order': '01', 'category': 'CIRCULAR GAUGE', 'type': 'new' },
    { 'path': 'circular-gauge/direction', 'component':'Direction', 'name': 'Direction Compass', 'description':'This demo for Essential JS2 Circular Gauge control illustrates how to make a direction compass by using the circular gauge.', 'order': '01', 'category': 'CIRCULAR GAUGE' },
    { 'path': 'circular-gauge/axes', 'component':'Axes', 'name': 'Multiple Axis', 'description':'This demo for Essential JS2 Circular Gauge control visualizes the circular gauge with multiple axes.', 'order': '03', 'category': 'AXES' },
    { 'path': 'circular-gauge/drag', 'component':'Drag', 'name': 'Pointer Drag', 'description':'This demo for Essential JS2 Circular Gauge control visualizes the pointer drag support and its options.', 'order': '04', 'category': 'USER INTERACTION' },
    { 'path': 'circular-gauge/tooltip', 'component':'Tooltip', 'name': 'Tooltip', 'description':'This demo for Essential JS2 Circular Gauge control visualizes the tooltip template for circular gauge pointer.', 'order': '04', 'category': 'USER INTERACTION' },
    { 'path': 'circular-gauge/image', 'component':'Image', 'name': 'Pointer Image', 'description':'This demo for Essential JS2 Circular Gauge control visualizes the short-put distance covered by the athletes by using the image pointer.', 'order': '02', 'category': 'POINTER' },
    { 'path': 'circular-gauge/pointers', 'component':'Pointers', 'name': 'Pointer Customization', 'description':'This demo for Essential JS2 Circular Gauge control visualizes the different types of pointers available in the circular gauge.', 'order': '02', 'category': 'POINTER' },
    { 'path': 'circular-gauge/sample-data', 'component':'SampleData', 'name': 'Data Sample', 'description':'This demo for Essential JS2 Circular Gauge control demonstrates live data, along with the data grid control.', 'order': '05', 'category': 'Live' },
    { 'path': 'circular-gauge/speedometer', 'component':'Speedometer', 'name': 'Speedometer', 'order': '05', 'category': 'Live', 'type': 'new' }
]