export const RibbonSampleOrder: Object = [
    { 'path': 'ribbon/default', 'component': 'Default', 'name': 'Default Functionalities', 'description': 'This sample explains and demonstrates the default functionalities of the Syncfusion React ribbon component.', 'order': '01', 'category': 'Ribbon', 'api': '{ "Ribbon":["tabs", "fileMenu"] }', 'sourceFiles': [{ 'displayName': 'default.tsx', 'path': 'src/ribbon/default.tsx' }, { 'displayName': 'default.jsx', 'path': 'src/ribbon/default.jsx' }, { 'displayName': 'default.css', 'path': 'src/ribbon/default.css' }] },
    { 'path': 'ribbon/simplified', 'component': 'Simplified', 'name': 'Simplified Mode', 'description': 'This sample demonstrates the simplified mode functionalities of the Syncfusion React ribbon component.', 'order': '01', 'category': 'Ribbon', 'api': '{ "Ribbon":["tabs", "fileMenu", "activeLayout"] }', 'sourceFiles': [{ 'displayName': 'simplified.tsx', 'path': 'src/ribbon/simplified.tsx' }, { 'displayName': 'simplified.jsx', 'path': 'src/ribbon/simplified.jsx' }, { 'displayName': 'simplified.css', 'path': 'src/ribbon/simplified.css' }] },
    { 'path': 'ribbon/backstage', 'component': 'Backstage', 'name': 'Backstage', 'description': 'This sample demonstrates the ribbon backstage functionalities of the Syncfusion React ribbon component.', 'order': '01', 'category': 'Ribbon', 'api': '{ "Ribbon":["tabs", "backstageMenu"] }', 'sourceFiles': [{ 'displayName': 'backstage.tsx', 'path': 'src/ribbon/backstage.tsx' }, { 'displayName': 'backstage.jsx', 'path': 'src/ribbon/backstage.jsx' }, { 'displayName': 'backstage.css', 'path': 'src/ribbon/backstage.css' }] },
    { 'path': 'ribbon/contextual', 'component': 'Contextual', 'name': 'Contextual Tabs', 'description': 'This sample demonstrates the contextual tab functionality of the Syncfusion Angular Ribbon component.', 'order': '01', 'category': 'Ribbon', 'api': '{ "Ribbon":["tabs", "fileMenu", "contextualTabs"] }', 'sourceFiles': [{ 'displayName': 'contextual.tsx', 'path': 'src/ribbon/contextual.tsx' }, { 'displayName': 'contextual.jsx', 'path': 'src/ribbon/contextual.jsx' }, { 'displayName': 'contextual.css', 'path': 'src/ribbon/contextual.css' }] },
    { 'path': 'ribbon/resize', 'component': 'Resize', 'name': 'Ribbon Resizing', 'description': 'This sample demonstrates the ribbon resizing functionalities of the Syncfusion React ribbon component.', 'order': '01', 'category': 'Ribbon', 'api': '{ "Ribbon":["tabs", "fileMenu"] }', 'sourceFiles': [{ 'displayName': 'resize.tsx', 'path': 'src/ribbon/resize.tsx' }, { 'displayName': 'resize.jsx', 'path': 'src/ribbon/resize.jsx' }, { 'displayName': 'resize.css', 'path': 'src/ribbon/resize.css' }] },
    { 'path': 'ribbon/keytip', 'component': 'KeyTip', 'name': 'Ribbon KeyTips', 'description': 'This sample demonstrates the ribbon keytip functionalities of the Syncfusion React ribbon component.', 'order': '01', 'category': 'Ribbon', 'api': '{ "Ribbon":["tabs", "backStageMenu", "enableKeyTips", "layoutSwitcherKeyTip", "created"] }', 'sourceFiles': [{ 'displayName': 'keytip.tsx', 'path': 'src/ribbon/keytip.tsx' }, { 'displayName': 'keytip.jsx', 'path': 'src/ribbon/keytip.jsx' }, { 'displayName': 'keytip.css', 'path': 'src/ribbon/keytip.css' }] },
    { 'path': 'ribbon/gallery', 'component': 'Gallery', 'name': 'Ribbon Gallery', 'description': 'This sample demonstrates the ribbon gallery functionalities of the Syncfusion React ribbon component.', 'order': '01', 'category': 'Ribbon', 'api': '{ "Ribbon":["tabs", "fileMenu", "cssClass"] }', 'sourceFiles': [{ 'displayName': 'gallery.tsx', 'path': 'src/ribbon/gallery.tsx' }, { 'displayName': 'gallery.jsx', 'path': 'src/ribbon/gallery.jsx' }, { 'displayName': 'gallery.css', 'path': 'src/ribbon/gallery.css' }] }
]
