export const ComboBoxSampleOrder:Object = [
    { 'path': 'combo-box/default', 'component':'Default', 'name': 'Default Functionalities', 'description': 'This demo for Syncfusion vue combo box component shows the default rendering with minimum configuration.', 'order': '01', 'category': 'ComboBox', 'api': '{"ComboBox": ["popupHeight", "index", "change", "placeholder"]}' },
    { 'path': 'combo-box/grouping-icon', 'component':'Grouping', 'name': 'Grouping and Icons', 'description': 'This demo shows the grouping based on different categories with individual header and icon support in the Syncfusion vue combo box component.', 'order': '01', 'category': 'ComboBox', 'api': '{"ComboBox": ["dataSource", "fields", "placeholder", "popupHeight"]}' },
    { 'path': 'combo-box/data-binding', 'component':'Data', 'name': 'Data Binding', 'description': 'This demo for Syncfusion vue combo box component shows how to bind with  local data source and how to fetch data from remote data service.', 'order': '01', 'category': 'ComboBox', 'api': '{"ComboBox": ["dataSource", "fields", "query", "sortOrder", "autofill", "popupHeight", "placeholder"]}' },
    { 'path': 'combo-box/custom-value', 'component':'Custom', 'name': 'Custom Value', 'description': 'This demo for Syncfusion vue combo box component demonstrates the addition of a new value that is not present in the predefined list.', 'order': '01', 'category': 'ComboBox', 'api': '{"ComboBox": ["dataSource", "fields", "placeholder", "popupHeight", "allowFiltering", "noRecordsTemplate", "filtering", "width"]}' },
    { 'path': 'combo-box/filtering', 'component':'Filtering', 'name': 'Filtering', 'description': 'This demo explains the filtering functionalities of the Syncfusion vue combo box component.', 'order': '01', 'category': 'ComboBox', 'api': '{"ComboBox": ["dataSource", "fields", "allowFiltering", "filtering", "placeholder", "popupHeight"]}' },
    { 'path': 'combo-box/template', 'component':'Templates', 'name': 'Templates', 'description': 'This demo shows on how to customize the appearance of each item in the pop-up list using template option in Syncfusion vue combo box component.', 'order': '01', 'category': 'ComboBox', 'api': '{"ComboBox": ["dataSource", "fields", "headerTemplate", "itemTemplate", "placeholder", "popupHeight"]}' },
    { 'path': 'combo-box/cascading', 'component':'Cascading', 'name': 'Cascading', 'description': 'This demo for Syncfusion vue combo box component shows the cascading support.', 'order': '01', 'category': 'ComboBox', 'api': '{"ComboBox": ["dataSource", "allowCustom", "fields", "change", "placeholder", "popupHeight", "value", "enabled"]}' },
    { 'path': 'combo-box/diacritics-filtering', 'component':'DiacriticsFiltering', 'name': 'Diacritics Filtering', 'description': 'This demo explains the diacritics filter functionality of the Syncfusion vue combo box component.', 'order': '01', 'category': 'ComboBox', 'api': '{"ComboBox": ["dataSource", "ignoreAccent", "placeholder","allowFiltering"]}' }
]