export const ComboBoxSampleOrder:Object = [
    { 'path': 'combo-box/default', 'component':'Default', 'name': 'Default Functionalities', 'order': '01', 'category': 'ComboBox', 'api': '{"ComboBox": ["popupHeight", "index", "change", "placeholder"]}' },
    { 'path': 'combo-box/grouping-icon', 'component':'Grouping', 'name': 'Grouping and Icons', 'order': '01', 'category': 'ComboBox', 'api': '{"ComboBox": ["dataSource", "fields", "placeholder", "popupHeight"]}' },
    { 'path': 'combo-box/data-binding', 'component':'Data', 'name': 'Data Binding', 'order': '01', 'category': 'ComboBox', 'api': '{"ComboBox": ["dataSource", "fields", "query", "sortOrder", "autofill", "popupHeight", "placeholder"]}' },
    { 'path': 'combo-box/custom-value', 'component':'Custom', 'name': 'Custom Value', 'order': '01', 'category': 'ComboBox', 'api': '{"ComboBox": ["dataSource", "fields", "placeholder", "popupHeight", "allowFiltering", "noRecordsTemplate", "filtering", "width"]}' },
    { 'path': 'combo-box/filtering', 'component':'Filtering', 'name': 'Filtering', 'order': '01', 'category': 'ComboBox', 'api': '{"ComboBox": ["dataSource", "fields", "allowFiltering", "filtering", "placeholder", "popupHeight"]}' },
    { 'path': 'combo-box/template', 'component':'Templates', 'name': 'Templates', 'order': '01', 'category': 'ComboBox', 'api': '{"ComboBox": ["dataSource", "fields", "headerTemplate", "itemTemplate", "placeholder", "popupHeight"]}' },
    { 'path': 'combo-box/cascading', 'component':'Cascading', 'name': 'Cascading', 'order': '01', 'category': 'ComboBox', 'api': '{"ComboBox": ["dataSource", "allowCustom", "fields", "change", "placeholder", "popupHeight", "value", "enabled"]}' },
    { 'path': 'combo-box/diacritics-filtering', 'component':'DiacriticsFiltering', 'name': 'Diacritics Filtering', 'order': '01', 'category': 'ComboBox', 'api': '{"ComboBox": ["dataSource", "ignoreAccent", "placeholder","allowFiltering"]}' }
]