export const BarcodeSampleOrder = [
    { 'path': 'barcode/ean8', 'component': 'Ean8', 'name': 'EAN-8', 'description': 'This sample visualizes the processing of an order placed using credit card with built-in flow shapes.', 'order': '01', 'category': 'Getting Started' },
    { 'path': 'barcode/code128', 'component': 'Code128', 'name': 'Code 128', 'description': 'This sample visualizes a barcode image that presents alphanumeric combinations and it consist of start character, data digits etc.', 'order': '01', 'category': 'Getting Started' },
    { 'path': 'barcode/code128A', 'component': 'Code128A', 'name': 'Code 128A', 'description': 'This sample visualizes a barcode image that presents information with a combination of numbers, and control characters such as tab and new line.', 'order': '01', 'category': 'Getting Started' },
    { 'path': 'barcode/code128B', 'component': 'Code128B', 'name': 'Code 128B', 'description': 'This sample visualizes a barcode image that presents information with a combination of numbers, and control characters such as tab and new line.', 'order': '01', 'category': 'Getting Started' },
    { 'path': 'barcode/code128C', 'component': 'Code128C', 'name': 'Code 128C', 'description': 'This sample visualizes a barcode image that presents information with a combination of numbers, uppercase and lowercase letters, and some additional characters.', 'order': '01', 'category': 'Getting Started' },
    { 'path': 'barcode/code93', 'component': 'Code93', 'name': 'Code 93', 'description': 'This sample has a native character set of 26 uppercase letters, 10 digits, and 7 special characters.', 'order': '01', 'category': 'Getting Started' },
    { 'path': 'barcode/code32', 'component': 'Code32', 'name': 'Code 32', 'description': 'This sample visualizes the pharmaceutical code that encodes numeric data in a compressed format and supports all numeric digits and all uppercase letters', 'order': '01', 'category': 'Getting Started' },
    { 'path': 'barcode/default-functionality', 'component': 'Default', 'name': 'Codabar', 'description': 'This sample visualizes the processing of an order placed using credit card with built-in flow shapes.', 'order': '01', 'category': 'Getting Started' },
    { 'path': 'barcode/ean13', 'component': 'Ean13', 'name': 'EAN-13', 'description': 'This sample visualizes the processing of an order placed using credit card with built-in flow shapes.', 'order': '01', 'category': 'Getting Started' },
    { 'path': 'barcode/upca', 'component': 'UpcA', 'name': 'UPC-A', 'description': 'This sample visualizes the processing of an order placed using credit card with built-in flow shapes.', 'order': '01', 'category': 'Getting Started' },
    { 'path': 'barcode/upce', 'component': 'UpcE', 'name': 'UPC-E', 'description': 'This sample visualizes the processing of an order placed using credit card with built-in flow shapes.', 'order': '01', 'category': 'Getting Started' },
    { 'path': 'barcode/code39', 'component': 'Code39', 'name': 'Code39', 'description': 'This sample visualizes the processing of an order placed using credit card with built-in flow shapes.', 'order': '01', 'category': 'Getting Started' },
    { 'path': 'barcode/code39Extd', 'component': 'Code39Extd', 'name': 'Code 39 Extended', 'description': 'This sample visualizes the processing of an order placed using credit card with built-in flow shapes.', 'order': '01', 'category': 'Getting Started' },
    { 'path': 'barcode/qrcode', 'component': 'QrCode', 'name': 'QR Code', 'description': 'This sample visualizes the processing of an order placed using credit card with built-in flow shapes.', 'order': '01', 'category': 'Getting Started' },
    { 'path': 'barcode/datamatrix', 'component': 'DataMatrix', 'name': 'Data Matrix', 'description': 'This sample visualizes the processing of an order placed using credit card with built-in flow shapes.', 'order': '01', 'category': 'Getting Started' }
];
