export const PivotViewSampleOrder: Object = [
    { 'path': 'pivot-table/default', 'component': 'Default', 'description': 'This demo for Essential JS2 Pivot Table control shows the basic rendering of the pivot table with minimum configuration', 'name': 'Default Functionalities', 'order': '01', 'category': 'Pivot Table', 'api': '{"PivotViewComponent":["DataSource"] }' },
    {
        'path': 'pivot-table/local', 'component': 'Local', 'description': 'This demo for Essential JS2 Pivot Table control demonstrate the basic rendering of the pivot table with local JSON or CSV data', 'name': 'Local Data', 'order': '02', 'category': 'Data Binding', 'api': '{"PivotViewComponent":["DataSource"]}', 
        'sourceFiles': [
            { 'displayName': 'local.tsx', 'path': 'src/pivot-table/local.tsx' },
            { 'displayName': 'local.jsx', 'path': 'src/pivot-table/local.jsx' },
            { 'displayName': 'localData.json', 'path': 'src/pivot-table/pivot-data/rData.json' },
            { 'displayName': 'csvData.json', 'path': 'src/pivot-table/pivot-data/csvData.ts' }
        ]
    },
    { 'path': 'pivot-table/remote', 'component': 'Remote', 'description': 'This demo for Essential JS2 Pivot Table control demonstrate the basic rendering of the pivot table with JSON or CSV remote data', 'name': 'Remote Data', 'order': '02', 'category': 'Data Binding', 'api': '{"PivotViewComponent":["DataSource"]}' },
    { 'path': 'pivot-table/olap', 'component': 'OlapSample', 'description': 'This demo for Essential JS2 Pivot Table control demonstrate the basic rendering of the pivot table with olap datasource', 'name': 'OLAP', 'order': '02', 'category': 'Data Binding', 'api': '{"PivotViewComponent":["DataSource"]}' },
    { 'path': 'pivot-table/pivot-chart', 'component': 'ChartIntegration', 'description': 'This demo for Essential JS2 Pivot Table control demonstrate integration of pivot table data into a simple pivot chart', 'name': 'Pivot Chart', 'order': '03', 'category': 'Integration', 'api': '{"PivotViewComponent":["DataSource"]}' },
    { 'path': 'pivot-table/external-binding', 'component': 'Integration', 'description': 'This demo for Essential JS2 Pivot Table control demonstrate the rendering of chart with cell selection option', 'name': 'External Binding', 'order': '03', 'category': 'Integration', 'api': '{"PivotViewComponent":["DataSource"]}' },
    { 'path': 'pivot-table/field-list', 'component': 'FieldList', 'description': 'This demo for Essential JS2 Pivot Table control demonstrate the field list feature of the pivot table', 'name': 'Field List', 'order': '04', 'category': 'User Interaction', 'api': '{"PivotViewComponent":["DataSource"] }' },
    { 'path': 'pivot-table/grouping-bar', 'component': 'GroupingBarSample', 'description': 'This demo for Essential JS2 Pivot Table control demonstrate the grouping bar feature of the pivot table', 'name': 'Grouping Bar', 'order': '04', 'category': 'User Interaction', 'api': '{"PivotViewComponent":["DataSource"] }' },
    { 'path': 'pivot-table/conditional-formatting', 'component': 'ConditionalFormattingClass', 'description': 'This demo for Essential JS2 Pivot Table control demonstrate formatting the appearance of the pivot table cells with values based on the applied conditions', 'name': 'Conditional Formatting', 'order': '04', 'category': 'User Interaction', 'api': '{"PivotViewComponent":["DataSource"] }' },
    { 'path': 'pivot-table/selection', 'component': 'Selection', 'description': 'This demo for Essential JS2 Pivot Table control demonstrate the cell selection feature of the pivot table', 'name': 'Selection', 'order': '04', 'category': 'User Interaction', 'api': '{"PivotViewComponent":["DataSource"] }' },
    { 'path': 'pivot-table/summary-customization', 'component': 'SummaryCustomization', 'description': 'This demo for Essential JS2 Pivot Table control demonstrate the summary customization feature of the pivot table', 'name': 'Show/Hide Totals', 'order': '04', 'category': 'User Interaction', 'api': '{"PivotViewComponent":["DataSource"] }' },
    { 'path': 'pivot-table/grouping', 'component': 'Grouping', 'description': 'This demo for Essential JS2 Pivot Table control demonstrate the grouping feature for date and number fields', 'name': 'Grouping', 'order': '04', 'category': 'User Interaction', 'api': '{"PivotViewComponent":["DataSource"] }' },
    { 'path': 'pivot-table/tool-bar', 'component': 'PivotToolbar', 'description': 'This demo for Essential JS2 Pivot Table control demonstrate the toolbar feature with pivot table and pivot chart', 'name': 'Toolbar', 'order': '04', 'category': 'User Interaction', 'api': '{"PivotViewComponent":["DataSource"] }' },
    { 'path': 'pivot-table/calculated-field', 'component': 'CalculatedFieldClass', 'description': 'This demo for Essential JS2 Pivot Table control shows calculated field, and it allows users to add calculated items', 'name': 'Calculated Field', 'order': '05', 'category': 'Formula', 'api': '{"PivotViewComponent":["DataSource"] }' },
    { 'path': 'pivot-table/aggregation', 'component': 'Aggregation', 'description': 'This demo for Essential JS2 Pivot Table control shows different types of aggregation for value fields', 'name': 'Aggregation', 'order': '05', 'category': 'Formula', 'type': 'update', 'api': '{"PivotViewComponent":["DataSource"] }' },
    { 'path': 'pivot-table/sorting', 'component': 'Sorting', 'description': 'This demo for Essential JS2 Pivot Table control shows ordering(sorting) of fields either in ascending or descending order', 'name': 'Default Sorting', 'order': '06', 'category': 'Sorting', 'api': '{"PivotViewComponent":["DataSource"]}' },
    { 'path': 'pivot-table/value-sorting', 'component': 'ValueSorting', 'description': 'This demo for Essential JS2 Pivot Table control shows sorting values on column or row wise in ascending or descending order', 'name': 'Value Sorting', 'order': '06', 'category': 'Sorting', 'api': '{"PivotViewComponent":["DataSource"] }' },
    { 'path': 'pivot-table/filtering', 'component': 'Filtering', 'description': 'This demo for Essential JS2 Pivot Table control demonstrate member filtering of field headers either by including or excluding them', 'name': 'Default Filtering', 'order': '07', 'category': 'Filtering', 'api': '{"PivotViewComponent":["DataSource"]}' },
    { 'path': 'pivot-table/label-filtering', 'component': 'LabelFilter', 'description': 'This demo for Essential JS2 Pivot Table control demonstrate label filtering of field headers either by including or excluding them', 'name': 'Label Filtering', 'order': '07', 'category': 'Filtering', 'api': '{"PivotViewComponent":["DataSource"]}' },
    { 'path': 'pivot-table/value-filtering', 'component': 'ValueFilter', 'description': 'This demo for Essential JS2 Pivot Table control demonstrate the filtering of field headers based on the grand total (value based)', 'name': 'Value Filtering', 'order': '07', 'category': 'Filtering', 'api': '{"PivotViewComponent":["DataSource"]}' },
    { 'path': 'pivot-table/virtual-scrolling', 'component': 'VirtualScrolling', 'description': 'This demo for Essential JS2 Pivot Table control shows virtual scrolling option available vertically and horizontally to load large records with ease', 'name': 'Virtual Scrolling', 'order': '08', 'category': 'Scrolling', 'api': '{"PivotViewComponent":["DataSource"] }' },
    { 'path': 'pivot-table/cell-template', 'component': 'CellTemplate', 'description': 'This demo for Essential JS2 Pivot Table control demonstrate cell template option on cells of the pivot table', 'name': 'Cell Template', 'order': '09', 'category': 'Customization', 'api': '{"PivotViewComponent":["DataSource"] }' },
    { 'path': 'pivot-table/drill-through', 'component': 'DrillThroughComponent', 'description': 'This demo for Essential JS2 Pivot Table control shows the raw items of any value cells in pivot table', 'name': 'Drill Through', 'order': '10', 'category': 'Miscellaneous', 'api': '{"PivotViewComponent":["DataSource"] }' },
    { 'path': 'pivot-table/editing', 'component': 'Editing', 'description': 'This demo for Essential JS2 Pivot Table control allows to edit, add and delete the value cells in pivot table', 'name': 'Editing', 'order': '10', 'category': 'Miscellaneous', 'api': '{"PivotViewComponent":["DataSource"] }' },
    { 'path': 'pivot-table/hyper-link', 'component': 'HyperLink', 'description': 'This demo for Essential JS2 Pivot Table control shows hyperlink options in row headers, column headers, value cells, and summary cells in the pivot table', 'name': 'Hyperlink', 'order': '10', 'category': 'Miscellaneous', 'api': '{"PivotViewComponent":["DataSource"] }' },
    { 'path': 'pivot-table/defer-update', 'component': 'DeferUpdate', 'description': 'This demo for Essential JS2 Pivot Table control demonstrate defer layout update feature of the pivot table', 'name': 'Defer Layout Update', 'order': '10', 'category': 'Miscellaneous', 'api': '{"PivotViewComponent":["DataSource"] }' },
    { 'path': 'pivot-table/exporting', 'component': 'Exporting', 'description': 'This demo for Essential JS2 Pivot Table control demonstrate client-side exporting of the pivot table to Excel, CSV and PDF formats', 'name': 'Export', 'order': '10', 'category': 'Miscellaneous', 'api': '{"PivotViewComponent":["DataSource"] }' }
];