export const BadgeSampleOrder: Object = [
    { 'path': 'badge/default', 'component': 'Default', 'name': 'Default', 'description': 'Demo of the pure CSS Essential JS 2 Badge component displaying a notification count in a group button.', 'order': '01', 'category': 'Badge', 'sourceFiles': [
        { 'displayName': 'default.tsx', 'path': 'src/badge/default.tsx' },{ 'displayName': 'default.jsx', 'path': 'src/badge/default.jsx' },{ 'displayName': 'default.css', 'path': 'src/badge/default.css' }] },
    { 'path': 'badge/types', 'component': 'Types', 'name': 'Types', 'description': 'Demo of the pure CSS Essential JS 2 Badge components badge types: primary, secondary, success, danger, warning, info, light, and dark.', 'order': '01', 'category': 'Badge', 'sourceFiles': [
        { 'displayName': 'types.tsx', 'path': 'src/badge/types.tsx' },{ 'displayName': 'types.jsx', 'path': 'src/badge/types.jsx' },{ 'displayName': 'types.css', 'path': 'src/badge/types.css' }] },
    { 'path': 'badge/notification', 'component': 'Notification', 'name': 'Notification',  'description': 'Demo of the pure CSS Essential JS 2 Badge component displaying notifications on popular social media logos such as Facebook, WhatsApp, Twitter, and others.', 'order': '01', 'category': 'Badge', 'sourceFiles': [
        { 'displayName': 'notification.tsx', 'path': 'src/badge/notification.tsx' },{ 'displayName': 'notification.jsx', 'path': 'src/badge/notification.jsx' },{ 'displayName': 'notification.css', 'path': 'src/badge/notification.css' }] },
    { 'path': 'badge/listview', 'component': 'ListView', 'name': 'ListView', 'description': 'Demo integrating the Essential JS 2 Badge and ListView components to display a notification count in a list item to achieve a Gmail-like user interface.', 'order': '02', 'category': 'Integration', 'sourceFiles': [
        { 'displayName': 'listview.tsx', 'path': 'src/badge/listview.tsx' },{ 'displayName': 'listview.jsx', 'path': 'src/badge/listview.jsx' },{ 'displayName': 'listview.css', 'path': 'src/badge/listview.css' },{ 'displayName': 'listData.ts', 'path': 'src/badge/listData.ts' }] },
    { 'path': 'badge/accordion', 'component': 'Accordion', 'name': 'Accordion', 'description': 'Demo integrating the Essential JS 2 Badge and Accordion components to display an unread notification count in a header to achieve an Outlook-like user interface', 'order': '02', 'category': 'Integration', 'sourceFiles': [
        { 'displayName': 'accordion.tsx', 'path': 'src/badge/accordion.tsx' },{ 'displayName': 'accordion.jsx', 'path': 'src/badge/accordion.jsx' },{ 'displayName': 'accordion.css', 'path': 'src/badge/accordion.css' }] },
    { 'path': 'badge/toolbar', 'component': 'Toolbar', 'name': 'Toolbar', 'description': 'Demo integrating the Essential JS 2 Badge and ToolBar components to display important information in a mobile application header.', 'order': '02', 'category': 'Integration', 'sourceFiles': [
        { 'displayName': 'toolbar.tsx', 'path': 'src/badge/toolbar.tsx' },{ 'displayName': 'toolbar.jsx', 'path': 'src/badge/toolbar.jsx' },{ 'displayName': 'toolbar.css', 'path': 'src/badge/toolbar.css' }] }
]
