export const MapSampleOrder:Object = [
    { 'path': 'maps/default', 'component':'DefaultMaps', 'name': 'Default Functionalities', 'description':'This demo for Essential JS2 Maps control visualizes the continents in the world by rendering those in a map layer.', 'order': '01', 'category': 'Maps' },
    { 'path': 'maps/projection', 'component':'ProjectionMaps', 'name': 'Projection', 'description':'This demo for Essential JS2 Maps control shows the details of permanent and non-permanent countries in the UN Security Council, in 2017.', 'order': '02', 'category': 'Features' },
    { 'path': 'maps/multilayer', 'component':'MultilayerMaps', 'name': 'Multi-layers', 'description':'This demo for Essential JS2 Maps control depicts the layer along with sublayers for California and Texas.', 'order': '02', 'category': 'Features' },
    { 'path': 'maps/marker', 'component':'MarkerMaps', 'name': 'Marker', 'description':'This demo for Essential JS2 Maps control shows the top 25 populated cities in the world by displaying the markers in their locations.', 'order': '02', 'category': 'Features' },
    { 'path': 'maps/marker-template', 'component':'MarkerTemplateMaps', 'name': 'Marker template', 'description':'This demo for Essential JS2 Maps control indicates the temperature of various cities of Australia in marker templates.', 'order': '02', 'category': 'Features' },
    { 'path': 'maps/label', 'component':'LabelMaps', 'name': 'Labels', 'description':'This demo for Essential JS2 Maps control shows the names of all the states in USA in data label. Intersect action and smart labels mode can be changed.', 'order': '02', 'category': 'Features' },
    { 'path': 'maps/bubble', 'component':'BubbleMaps', 'name': 'Bubble', 'description':'This demo for Essential JS2 Maps control illustrates the top 30 countries which has highest Internet users in bubbles of the year 2016.', 'order': '02', 'category': 'Features' },
    { 'path': 'maps/navigation-line', 'component':'NavigationLineMaps', 'name': 'Navigation Lines', 'description':'This demo for Essential JS2 Maps control illustrates the sea routes between various cities for shipping.', 'order': '02', 'category': 'Features' },
    { 'path': 'maps/legend', 'component':'LegendMaps', 'name': 'Legend', 'description':'This demo for Essential JS2 Maps control visualizes grouping of countries in the legend based on its population density.', 'order': '02', 'category': 'Features', 'type': 'update' },
    { 'path': 'maps/color-mapping', 'component':'ColorMap', 'name': 'Color Mapping', 'order': '02', 'category': 'Features', 'type': 'new' },
    { 'path': 'maps/annotation', 'component':'AnnotationMaps', 'name': 'Annotations', 'description':'This demo for Essential JS2 Maps control depicts the facts about Africa continent and a direction compass in an annotation.', 'order': '02', 'category': 'Features' },
    { 'path': 'maps/osm', 'component':'OSMMaps', 'name': 'OpenStreetMap', 'order': '03', 'category': 'Map Providers', 'type': 'new' },
    { 'path': 'maps/osm-with-navigation-lines', 'component':'OSMNavigation', 'name': 'OSM with Navigation Lines', 'order': '03', 'category': 'Map Providers', 'type': 'new' },
    { 'path': 'maps/osm-with-sublayers', 'component':'OSMSubLayer', 'name': 'OSM with Sublayer', 'order': '03', 'category': 'Map Providers', 'type': 'new' },
    { 'path': 'maps/tooltip', 'component':'TooltipMaps', 'name': 'Tooltip', 'description':'This demo for Essential JS2 Maps control depicts the countries that were appeared in the finals of Cricket World Cup and their counts.', 'order': '04', 'category': 'User Interaction' },
    { 'path': 'maps/selection', 'component':'SelectionMaps', 'name': 'Selection & Highlight', 'description':'This demo for Essential JS2 Maps control visualizes USA president election results in the year 2016. Default and interactive are the two types of legend.', 'order': '04', 'category': 'User Interaction' },
    { 'path': 'maps/zooming', 'component':'ZoomingMaps', 'name': 'Zooming & Panning', 'description':'This demo for Essential JS2 Maps control depicts the properties required to zoom and pan the rendered map.', 'order': '04', 'category': 'User Interaction' },
    { 'path': 'maps/drilldown', 'component':'DrilldownMaps', 'name': 'Drill down', 'description':'This demo for Essential JS2 Maps control demonstrates drill down with all the continents in the initial view and countries on drill.', 'order': '04', 'category': 'User Interaction' },

    { 'path': 'maps/print', 'component':'PrintMaps', 'name': 'Print', 'description':'This demo for Essential JS2 Maps control illustrates the printing functionality in the maps control.', 'order': '05', 'category': 'Print and Export' },
    { 'path': 'maps/export', 'component':'ExportMaps', 'name': 'Export', 'description':'This demo for Essential JS2 Maps control illustrates the exporting functionality in the maps control.', 'order': '05', 'category': 'Print and Export' },

    { 'path': 'maps/heatmap', 'component':'HeatMaps', 'name': 'Heat Map', 'description':'This demo for Essential JS2 Maps control visualizes the state wise population of India in the year 2011. Color for states will be applied based on its value.', 'order': '06', 'category': 'Use Cases' },
    { 'path': 'maps/curved', 'component':'CurvedMaps', 'name': 'Flight routes', 'description':'This demo for Essential JS2 Maps control demonstrates the flight routes from India to China using navigation lines feature.', 'order': '06', 'category': 'Use Cases' },
    { 'path': 'maps/earthquake', 'component':'EarthquakeMaps', 'name': 'Earthquake indication', 'description':'This demo for Essential JS2 Maps control demonstrates the earth quack occurred in Sumatra, Indonesia in the year 2009.', 'order': '06', 'category': 'Use Cases' },
    { 'path': 'maps/highlight', 'component':'HighlightMaps', 'name': 'Highlighted region', 'description':'This demo for Essential JS2 Maps control depicts the ATM populated areas in Oklahoma by highlighting the regions.', 'order': '06', 'category': 'Use Cases' },
    { 'path': 'maps/map-pie', 'component':'PieMaps', 'name': 'Map with Pie chart', 'description':'This demo for Essential JS2 Maps control visualizes the placing of pie charts on the maps using marker templates.', 'order': '06', 'category': 'Use Cases' },
    { 'path': 'maps/map-with-slider', 'component':'MapSlider', 'name': 'Map with Slider', 'order': '06', 'category': 'Use Cases', 'type': 'new' },
    { 'path': 'maps/seat-booking', 'component':'SeatBookingMaps', 'name': 'Bus seat booking', 'description':'This demo for Essential JS2 Maps control demonstrates the rendering of normal geometry type shapes on the map.', 'order': '06', 'category': 'Use Cases' }
   
];