export const ListViewSampleOrder: Object = [
    { 'path': 'listview/default', 'component': 'Default', 'name': 'Default Functionalities', 'description': 'Demo of Essential JS 2 ListView control default renderings of flat and group list views. Click any list item to select and highlight it.', 'order': '01', 'category': 'ListView', 'api': '{"ListViewComponent": ["dataSource", "fields", "appendTo"]}' },
    { 'path': 'listview/remote-list', 'component': 'Remote', 'name': 'Remote Data', 'description': 'Demo of Essential JS 2 ListView control rendering the list view with remote data, which uses DataManager and query properties to fetch data.', 'order': '01', 'category': 'ListView', 'api': '{"ListViewComponent": ["dataSource", "fields", "headerTitle", "showHeader", "query", "appendTo"]}' },
    { 'path': 'listview/check-list', 'component': 'Checklist', 'name': 'Checklist', 'description': 'Essential JS 2 ListView control demo of the checked list view, which supports selecting more than one list item.', 'order': '01', 'category': 'ListView', 'api': '{"ListViewComponent": ["dataSource", "fields", "headerTitle", "showHeader", "showIcon", "appendTo"]}' },
    { 'path': 'listview/nested-list', 'component': 'Nested', 'name': 'Nested List', 'description': 'Demo of Essential JS 2 ListView control showing the visual representation of nested data using the child property.', 'order': '01', 'category': 'ListView', 'api': '{"ListViewComponent": ["dataSource", "fields", "showCheckBox", "appendTo"]}' },
    { 'path': 'listview/virtualization', 'component': 'UiVirtualization', 'name': 'Virtualization', 'description': 'Demo of Essential JS 2 ListView control loading items in the view port with virtualization, which improves performance when loading large amounts of data.', 'order': '01', 'category': 'ListView', 'type': 'update', 'api': '{"ListViewComponent": ["dataSource", "fields", "headerTitle", "height", "showHeader", "enableVirtualization", "actionComplete", "actionBegin", "template", "appendTo"]}' },
    { 'path': 'listview/template', 'component': 'Template', 'name': 'Template', 'description': 'Demo of Essential JS 2 ListView control rendering customized elements inside list items. This sample is a news feed application built using a list view.', 'order': '02','type': 'update', 'category': 'Customization', 'api': '{"ListViewComponent": ["dataSource", "fields", "headerTitle", "showHeader", "template", "appendTo"]}' },
    { 'path': 'listview/group-template', 'component': 'GroupTemplate', 'name': 'Group Template','type': 'update', 'description': 'Essential JS 2 ListView control demo of list item and header customization using a template. The mobile settings showcase built-in CSS.', 'order': '02', 'category': 'Customization', 'api': '{"ListViewComponent": ["dataSource", "fields", "headerTitle", "showHeader", "template", "groupTemplate", "appendTo"]}' },
    { 'path': 'listview/call-history', 'component': 'CallHistory', 'name': 'Call History','type': 'update', 'description': 'Demo of Essential JS 2 ListView control in a real-world use case as a call history app, featuring mobile contacts, mail inbox, and more.', 'order': '03', 'category': 'Use Case', 'api': '{"ListViewComponent": ["dataSource", "fields", "select", "showIcon", "appendTo"]}' }
]